In [1]:
import pandas as pd
import numpy as np
import csv
import re

pd.set_option('display.max_columns', 500)
pd.set_option("display.max_rows", 101)

# A. Loading the Data

In [2]:
# 2018 Data

q1_2018 = pd.read_csv("Quarterly Files/2018Q1.csv", encoding='ISO-8859-1', sep='|', error_bad_lines=False)
q2_2018 = pd.read_csv("Quarterly Files/2018Q2.csv", encoding='ISO-8859-1', sep='|', error_bad_lines=False)
q3_2018 = pd.read_csv("Quarterly Files/2018Q3.csv", encoding='ISO-8859-1', sep='|', error_bad_lines=False)
q4_2018 = pd.read_csv("Quarterly Files/2018Q4.csv", encoding='ISO-8859-1', sep='|', error_bad_lines=False)
q1_2019 = pd.read_csv("Quarterly Files/2019Q1.csv", encoding='ISO-8859-1', sep='|', error_bad_lines=False)
q2_2019 = pd.read_csv("Quarterly Files/2019Q2.csv", encoding='ISO-8859-1', sep='|', error_bad_lines=False)

q3_2019 = pd.read_csv("Quarterly Files/2019Q3.csv", encoding='ISO-8859-1', sep='|', error_bad_lines=False)

q4_2019 = pd.read_csv("Quarterly Files/2019Q4.csv", encoding='ISO-8859-1', sep='|', error_bad_lines=False)

q1_2020 = pd.read_csv("Quarterly Files/2020Q1.csv", encoding='ISO-8859-1', sep='|', error_bad_lines=False)


april_2020 = pd.read_csv("Quarterly Files/2020_April.csv", encoding='ISO-8859-1', sep='|', error_bad_lines=False)


May_June_2020 = pd.read_csv("Quarterly Files/20200501_thru_20200630.csv", encoding='ISO-8859-1', sep='|', error_bad_lines=False)

q3_2020 = pd.read_csv("Quarterly Files/2020Q3.csv", encoding='ISO-8859-1', sep='|', error_bad_lines=False)

q4_2020 = pd.read_csv("Quarterly Files/2020Q4.csv", encoding='ISO-8859-1', sep='|', error_bad_lines=False)

b'Skipping line 107331: expected 82 fields, saw 93\n'
b'Skipping line 453688: expected 82 fields, saw 93\n'
b'Skipping line 488460: expected 82 fields, saw 93\n'
b'Skipping line 519666: expected 82 fields, saw 93\n'
/Users/jasonlim/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3147: DtypeWarning: Columns (80) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
b'Skipping line 640513: expected 82 fields, saw 93\n'
/Users/jasonlim/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3147: DtypeWarning: Columns (53,54,80) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
b'Skipping line 97231: expected 82 fields, saw 93\n'
b'Skipping line 513934: expected 82 fields, saw 93\n'
/Users/jasonlim/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3147: DtypeWarning: Columns (21,29,30,31,32,33,34,35,36,37,38,39,40,41,42,80) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
b'Skipping line 488687: expected 82 fields, saw 93\n'
/Users/jasonlim/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3147: DtypeWarning: Columns (21,29,30,31,32,33,34,35,36,37,38,39,40,41,42,46) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
b'Skipping line 45044: expected 82 fields, saw 93\n'
b'Skipping line 267975: expected 82 fields, saw 93\n'
b'Skipping line 336121: expected 82 fields, saw 93\n'
b'Skipping line 504972: expected 82 fields, saw 93\n'
b'Skipping line 739790: expected 82 fields, saw 93\n'
b'Skipping line 252446: expected 82 fields, saw 93\n'
b'Skipping line 20936: expected 82 fields, saw 93\n'
b'Skipping line 110321: expected 82 fields, saw 93\n'
/Users/jasonlim/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3147: DtypeWarning: Columns (20,29,30,31,32,33,34,35,36,37,38,39,40,41,42,80) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
b'Skipping line 321425: expected 82 fields, saw 93\n'
/Users/jasonlim/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3147: DtypeWarning: Columns (20,21,29,30,31,32,33,34,35,36,37,38,39,40,41,42,45,46,80) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
b'Skipping line 269296: expected 82 fields, saw 93\n'
b'Skipping line 482533: expected 82 fields, saw 93\n'
b'Skipping line 643254: expected 82 fields, saw 93\n'
b'Skipping line 93760: expected 82 fields, saw 93\n'
b'Skipping line 387924: expected 82 fields, saw 93\n'
b'Skipping line 400810: expected 82 fields, saw 93\n'
b'Skipping line 2004: expected 82 fields, saw 93\n'
b'Skipping line 231064: expected 82 fields, saw 93\n'
b'Skipping line 368179: expected 82 fields, saw 104\n'
b'Skipping line 641285: expected 82 fields, saw 93\n'
b'Skipping line 667593: expected 82 fields, saw 93\n'
b'Skipping line 822195: expected 82 fields, saw 93\n'
b'Skipping line 871735: expected 82 fields, saw 93\n'
b'Skipping line 900828: expected 82 fields, saw 93\n'
b'Skipping line 368565: expected 82 fields, saw 93\n'
b'Skipping line 667921: expected 82 fields, saw 93\n'

# B. Combining the Data

##  2018 check up
We think that K2 later updated the model_title_cnt and model_content_cnt fields for earlier files (2018 data).

So, we want to make sure this changes.

In [3]:
frames = [q1_2018, q2_2018,q3_2018,q4_2018]
final_df_2018 =pd.concat(frames, ignore_index=True)

In [4]:
final_df_2018.head()

,uid,store_id,post_id,listed_date,title,category,firearm_type,County,location,action,manufacturer,caliber,registered_date,price_num,sale_type,post_content,City,State,State_id,city_lat,city_lng,state_lat,state_lng,final_lat,final_lng,extract_date,post_url,firearm_accessories,sale_buy,uid_Change,store_id_Change,category_Change,firearm_type_Change,action_Change,manufacturer_Change,caliber_Change,registered_date_Change,sale_type_Change,listed_date_Change,location_Change,price_num_Change,post_content_Change,title_Change,Model_Title_Cnt,Model_Content_Cnt,Feature_Title_Cnt,Feature_Content_Cnt,Exclude_Title_Cnt,Exclude_Content_Cnt,Model_Title,Model_Content,Feature_Title,Feature_Content,Exclude_Title,Exclude_Content,action_exclusion,Model_Title_hit,Model_Content_hit,Feature_Title_hit,Feature_Content_hit,Exclude_Title_hit,Exclude_Content_hit,UniquePostIdFlag,RecordCount,DupeRemoveFlag,uid_ChangeCount,store_id_ChangeCount,listed_date_ChangeCount,title_ChangeCount,category_ChangeCount,firearm_type_ChangeCount,location_ChangeCount,action_ChangeCount,manufacturer_ChangeCount,caliber_ChangeCount,registered_date_ChangeCount,price_num_ChangeCount,sale_type_ChangeCount,post_content_ChangeCount,data_filter,dup_filter_group,post_process
0,116028,NaN,7769732,2018-01-07,For Sale: Small Collection of German Handguns.,Handguns,Pistol,Greene,"SPFD, Springfield, Missouri",NaN,NaN,NaN,NaN,1.0,Private Party,Small Collection of German Handguns. 7 Lugers ...,Springfield,Missouri,MO,37.258072,-93.343674,38.310318,-92.421555,37.258072,-93.343674,2018-01-07 16:03:34.680000000,http://www.armslist.com/posts/7769732,Firearms,For Sale,False,False,False,False,False,False,False,False,False,True,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.000000e+04,K2,0.0
1,115037,NaN,7767216,2018-01-07,For Sale/Trade: 300AAC AR15 Pistol Upper,Handguns,Pistol,Madison,"Huntsville, Huntsville, Alabama",Single Action,Anderson Manufacturing,NaN,2014-02-09,400.0,Private Party,"300AAC AR15 Pistol Upper:ALG 10"" RailNoveske K...",Huntsville,Alabama,AL,34.733963,-86.522911,32.609589,-86.729843,34.733963,-86.522911,2018-01-07 16:03:35.987000000,http://www.armslist.com/posts/7767216,Firearms,For Sale,True,True,True,True,True,True,True,True,True,True,True,True,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.111111e+13,NaN,0.0
2,115037,NaN,7767236,2018-01-07,For Sale: S&W Model 36-10 Revolver,Handguns,Revolver,Madison,"Huntsville, Huntsville, Alabama",Double / Single Action,Smith & Wesson,38 S&W Special,2014-02-09,550.0,Private Party,S&W Model 36-10 RevolverPurchased new Summer 2...,Huntsville,Alabama,AL,34.733963,-86.522911,32.609589,-86.729843,34.733963,-86.522911,2018-01-07 16:03:36.943000000,http://www.armslist.com/posts/7767236,Firearms,For Sale,False,False,False,False,False,False,False,False,False,True,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000e+04,K2,0.0
3,99474,NaN,7772635,2018-01-07,For Sale: Glock 19 Gen 4 with front serrations,Handguns,Pistol,Hillsborough,"Dover, Tampa/St. Pete, Florida",Striker Fire,Glock,9mm Luger (9x19),2017-07-25,550.0,Private Party,LNIB. Has front serrations from factory. Pol...,Dover,Florida,FL,27.975742,-82.240417,27.771553,-83.772789,27.975742,-82.240417,2018-01-07 16:03:37.730000000,http://www.armslist.com/posts/7772635,Firearms,For Sale,True,True,True,True,True,True,True,True,True,True,True,True,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.111111e+13,NaN,0.0
4,3319,NaN,6640627,2018-01-07,For Sale: SW 625JM,Handguns,Revolver,San Francisco,"Martinez, San Francisco, California",Double / Single Action,Smith & Wesson,45 ACP,2015-07-08,800.0,Private Party,I have a smith and wesson model 625 JM for sal...,San Francisco,California,CA,37.784828,-122.727800,37.286072,-119.279170,37.784828,-122.727800,2018-01-07 16:03:38.520000000,http://www.armslist.com/posts/6640627,Firearms,For Sale,False,False,False,False,False,False,False,False,False,True,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000e+04,K2,0.0

In [5]:
df_2018 = final_df_2018[
                   (final_df_2018['category']=="Rifles")&
                   (final_df_2018['DupeRemoveFlag']!=1)&
                   (final_df_2018['sale_buy']=="For Sale")&
                    (final_df_2018['sale_type']=="Private Party")
                  ]

In [6]:
conditions = [
    df_2018['category'].eq('Handguns'),
    df_2018['category'].eq("Rifles")& (df_2018['Model_Content_Cnt'].isnull()& \
    df_2018['Model_Title_Cnt'].isnull()),
    df_2018['category'].eq("Shotguns"),
    df_2018['category'].eq("Rifles")& (df_2018['Model_Content_Cnt'].notna() | \
                                             df_2018['Model_Title_Cnt'].notna())
]

choices = ["Handguns", "Rifles", "Shotguns", "Assault-style Rifles"]

df_2018['ET_Firearm_Type'] =  np.select(conditions, choices,default='Not_Firearm')

/Users/jasonlim/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':

In [7]:
df_2018['ET_Firearm_Type'].value_counts()

Rifles                  405333
Assault-style Rifles    172851
Name: ET_Firearm_Type, dtype: int64

I checked the 2018 data with current logic and the 2018 Unchecked dashboard. <br>
From the 2018 Unchecked dashboard, I see that 469,095 rifles and 109,138 assault-style rifles from 'for sale' and 'Unlicensed Seller'. <br>
On the other hand, the numbers that I have from my logics for 2018 are different.
I have 405,333 rifles and 172, 851 assault-style rifles from for sale and unlicensed seller.
So, as you mentioned, I can change back to your original logic and those numbers are correct (for this category issue)

In [8]:
firearm = ['Handguns', 'Rifles', 'Shotguns']
firearm_other = ['Gun Parts', 'Ammo', 'Magazines', 'Reloading', 'Antique Firearms', 'Tactical Gear', 
                 'Holsters',  'Muzzle Loaders', 'NFA Firearms', 'Gun Safes', 'Firearms Training']
non_firearm = ['Optics', 'Miscellaneous', 'Knievs', 'Archery', 'Vehicles', 'Air Guns', 
               'Targets and Range Equipment', 'Hunting Gear', 'Services', 'Events', 'Farming Equipment', 
               'Fishing Gear', 'Paintball/Airsoft', 'All Categories']

#Create a column called category_grouping for 3 groups, Firearm, Firearm_Other, Non-Firearm.

def cate_group(df):
    if df['category'] in firearm :
        return "Firearm Post"
    elif df['category'] in firearm_other:
        return "Firearm_Other Post"
    else:
        return "Non_Firearm Post"
    
    # For whole data
final_df_2018['Category_Group'] = final_df_2018.apply(cate_group, axis=1)

In [9]:
conditions = [
    final_df_2018['category'].eq('Handguns'),
    final_df_2018['category'].eq("Rifles")& (final_df_2018['Model_Content_Cnt'].isnull()& \
    final_df_2018['Model_Title_Cnt'].isnull()),
    final_df_2018['category'].eq("Shotguns"),
    final_df_2018['category'].eq("Rifles")& (final_df_2018['Model_Content_Cnt'].notna() | \
                                             final_df_2018['Model_Title_Cnt'].notna())
]

choices = ["Handguns", "Rifles", "Shotguns", "Assault-style Rifles"]

final_df_2018['ET_Firearm_Type'] =  np.select(conditions, choices,default='Not_Firearm')

In [10]:
len(final_df_2018[(final_df_2018['DupeRemoveFlag']!=1)&
              (final_df_2018['sale_buy']=="For Sale")&(final_df_2018['sale_type']=="Private Party")&
                  (final_df_2018['ET_Firearm_Type']!="Not_Firearm") &
                    (final_df_2018['State'] != 'Puerto Rico')&
                    (final_df_2018['State'] != 'Guam')])

1482973

In [11]:
frames = [q1_2018, q2_2018,q3_2018,q4_2018,
          q1_2019, q2_2019, q3_2019, q4_2019, 
          q1_2020, april_2020, May_June_2020, q3_2020, q4_2020]
final_df = pd.concat(frames, ignore_index=True)

In [12]:
final_df.head()

,uid,store_id,post_id,listed_date,title,category,firearm_type,County,location,action,manufacturer,caliber,registered_date,price_num,sale_type,post_content,City,State,State_id,city_lat,city_lng,state_lat,state_lng,final_lat,final_lng,extract_date,post_url,firearm_accessories,sale_buy,uid_Change,store_id_Change,category_Change,firearm_type_Change,action_Change,manufacturer_Change,caliber_Change,registered_date_Change,sale_type_Change,listed_date_Change,location_Change,price_num_Change,post_content_Change,title_Change,Model_Title_Cnt,Model_Content_Cnt,Feature_Title_Cnt,Feature_Content_Cnt,Exclude_Title_Cnt,Exclude_Content_Cnt,Model_Title,Model_Content,Feature_Title,Feature_Content,Exclude_Title,Exclude_Content,action_exclusion,Model_Title_hit,Model_Content_hit,Feature_Title_hit,Feature_Content_hit,Exclude_Title_hit,Exclude_Content_hit,UniquePostIdFlag,RecordCount,DupeRemoveFlag,uid_ChangeCount,store_id_ChangeCount,listed_date_ChangeCount,title_ChangeCount,category_ChangeCount,firearm_type_ChangeCount,location_ChangeCount,action_ChangeCount,manufacturer_ChangeCount,caliber_ChangeCount,registered_date_ChangeCount,price_num_ChangeCount,sale_type_ChangeCount,post_content_ChangeCount,data_filter,dup_filter_group,post_process
0,116028.0,NaN,7769732,2018-01-07,For Sale: Small Collection of German Handguns.,Handguns,Pistol,Greene,"SPFD, Springfield, Missouri",NaN,NaN,NaN,NaN,1.0,Private Party,Small Collection of German Handguns. 7 Lugers ...,Springfield,Missouri,MO,37.258072,-93.343674,38.310318,-92.421555,37.258072,-93.343674,2018-01-07 16:03:34.680000000,http://www.armslist.com/posts/7769732,Firearms,For Sale,False,False,False,False,False,False,False,False,False,True,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.000000e+04,K2,0.0
1,115037.0,NaN,7767216,2018-01-07,For Sale/Trade: 300AAC AR15 Pistol Upper,Handguns,Pistol,Madison,"Huntsville, Huntsville, Alabama",Single Action,Anderson Manufacturing,NaN,2014-02-09,400.0,Private Party,"300AAC AR15 Pistol Upper:ALG 10"" RailNoveske K...",Huntsville,Alabama,AL,34.733963,-86.522911,32.609589,-86.729843,34.733963,-86.522911,2018-01-07 16:03:35.987000000,http://www.armslist.com/posts/7767216,Firearms,For Sale,True,True,True,True,True,True,True,True,True,True,True,True,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.111111e+13,NaN,0.0
2,115037.0,NaN,7767236,2018-01-07,For Sale: S&W Model 36-10 Revolver,Handguns,Revolver,Madison,"Huntsville, Huntsville, Alabama",Double / Single Action,Smith & Wesson,38 S&W Special,2014-02-09,550.0,Private Party,S&W Model 36-10 RevolverPurchased new Summer 2...,Huntsville,Alabama,AL,34.733963,-86.522911,32.609589,-86.729843,34.733963,-86.522911,2018-01-07 16:03:36.943000000,http://www.armslist.com/posts/7767236,Firearms,For Sale,False,False,False,False,False,False,False,False,False,True,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000e+04,K2,0.0
3,99474.0,NaN,7772635,2018-01-07,For Sale: Glock 19 Gen 4 with front serrations,Handguns,Pistol,Hillsborough,"Dover, Tampa/St. Pete, Florida",Striker Fire,Glock,9mm Luger (9x19),2017-07-25,550.0,Private Party,LNIB. Has front serrations from factory. Pol...,Dover,Florida,FL,27.975742,-82.240417,27.771553,-83.772789,27.975742,-82.240417,2018-01-07 16:03:37.730000000,http://www.armslist.com/posts/7772635,Firearms,For Sale,True,True,True,True,True,True,True,True,True,True,True,True,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.111111e+13,NaN,0.0
4,3319.0,NaN,6640627,2018-01-07,For Sale: SW 625JM,Handguns,Revolver,San Francisco,"Martinez, San Francisco, California",Double / Single Action,Smith & Wesson,45 ACP,2015-07-08,800.0,Private Party,I have a smith and wesson model 625 JM for sal...,San Francisco,California,CA,37.784828,-122.727800,37.286072,-119.279170,37.784828,-122.727800,2018-01-07 16:03:38.520000000,http://www.armslist.com/posts/6640627,Firearms,For Sale,False,False,False,False,False,False,False,False,False,True,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000e+04,K2,0.0

In [13]:
# test logic
# checking condition errors.

cochise = final_df[(final_df['County']=="Cochise")&
                   (final_df['State']=="Arizona")&
                   (final_df['category']=="Rifles")&
                   (final_df['DupeRemoveFlag']!=1)&
                   (final_df['sale_buy']=="For Sale")
                  ]

In [14]:
len(cochise)

897

In [15]:
cochise.head()

,uid,store_id,post_id,listed_date,title,category,firearm_type,County,location,action,manufacturer,caliber,registered_date,price_num,sale_type,post_content,City,State,State_id,city_lat,city_lng,state_lat,state_lng,final_lat,final_lng,extract_date,post_url,firearm_accessories,sale_buy,uid_Change,store_id_Change,category_Change,firearm_type_Change,action_Change,manufacturer_Change,caliber_Change,registered_date_Change,sale_type_Change,listed_date_Change,location_Change,price_num_Change,post_content_Change,title_Change,Model_Title_Cnt,Model_Content_Cnt,Feature_Title_Cnt,Feature_Content_Cnt,Exclude_Title_Cnt,Exclude_Content_Cnt,Model_Title,Model_Content,Feature_Title,Feature_Content,Exclude_Title,Exclude_Content,action_exclusion,Model_Title_hit,Model_Content_hit,Feature_Title_hit,Feature_Content_hit,Exclude_Title_hit,Exclude_Content_hit,UniquePostIdFlag,RecordCount,DupeRemoveFlag,uid_ChangeCount,store_id_ChangeCount,listed_date_ChangeCount,title_ChangeCount,category_ChangeCount,firearm_type_ChangeCount,location_ChangeCount,action_ChangeCount,manufacturer_ChangeCount,caliber_ChangeCount,registered_date_ChangeCount,price_num_ChangeCount,sale_type_ChangeCount,post_content_ChangeCount,data_filter,dup_filter_group,post_process
19209,126613.0,NaN,7598428,2018-01-10,For Sale: Ruger 10/22,Rifles,Rifle,Cochise,"Douglas, Arizona, United States",Semi-automatic,Ruger,22 Long Rifle,NaN,300.0,Private Party,I am selling my Ruger 10/22 Tapco. Veey nice l...,Douglas,Arizona,AZ,31.60408,-109.86619,34.162819,-111.91933,31.60408,-109.86619,2018-01-10 17:15:46.240000000,http://www.armslist.com/posts/7598428,Firearms,For Sale,True,True,True,True,True,True,True,True,True,True,True,True,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.111111e+13,NaN,0.0
22666,33452.0,NaN,7359315,2018-01-10,For Sale/Trade: Remington 700 ADL .270,Rifles,Rifle,Cochise,"Sierra Vista, Sierra Vista, Arizona",Bolt Action,Remington,270 Winchester,NaN,400.0,Private Party,Remington 700 ADLRifle comes with buttstock sl...,Sierra Vista,Arizona,AZ,31.81065,-109.99762,34.162819,-111.91933,31.81065,-109.99762,2018-01-11 02:43:12.230000000,http://www.armslist.com/posts/7359315,Firearms,For Sale,False,False,False,False,False,False,False,True,False,True,False,True,True,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,1.010110e+06,NaN,0.0
66431,134549.0,NaN,7841354,2018-01-17,For Sale/Trade: Sig mcx patrol 5.56,Rifles,Rifle,Cochise,"Sierra Vista, Sierra Vista, Arizona",Semi-automatic,Sig Sauer,5.56×45mm NATO,2016-07-21,1500.0,Private Party,sig mcx patrol 5.56. Keymod rail. Magpul mbu...,Sierra Vista,Arizona,AZ,31.81065,-109.99762,34.162819,-111.91933,31.81065,-109.99762,2018-01-17 14:26:34.730000000,http://www.armslist.com/posts/7841354,Firearms,For Sale,True,True,True,True,True,True,True,True,True,True,True,True,True,True,1.0,1.0,NaN,NaN,NaN,NaN,MCX,MCX,NaN,NaN,NaN,NaN,N,1.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.111111e+13,NaN,0.0
105238,134549.0,NaN,7841342,2018-01-22,For Sale/Trade: Ruger American Predator,Rifles,Rifle,Cochise,"Sierra Vista, Sierra Vista, Arizona",Bolt Action,Ruger,308/7.62 NATO,2016-07-21,400.0,Private Party,Ruger American Predator. 308. Just the rifle....,Sierra Vista,Arizona,AZ,31.81065,-109.99762,34.162819,-111.91933,31.81065,-109.99762,2018-01-22 23:43:34.413000000,http://www.armslist.com/posts/7841342,Firearms,For Sale,True,True,True,True,True,True,True,True,True,True,True,True,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.111111e+13,NaN,0.0
133582,146157.0,NaN,7855452,2018-01-26,For Sale: Norinco 7.62x39 sks,Rifles,Rifle,Cochise,"Sierra Vista, Sierra Vista, Arizona",Semi-automatic,Norinco,7.62x39,NaN,350.0,Private Party,norinco 7.62x39 SKS great condition shoots per...,Sierra Vista,Arizona,AZ,31.81065,-109.99762,34.162819,-111.91933,31.81065,-109.99762,2018-01-27 02:01:21.083000000,http://www.armslist.com/posts/7855452,Firearms,For Sale,True,True,True,True,True,True,True,True,True,True,True,True,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.111111e+13,NaN,0.0

Post ID 7598428 should be rifle and 7841354 should be assault rifle

In [16]:
conditions = [
    cochise['category'].eq('Handguns'),
    cochise['category'].eq("Rifles")& (cochise['Model_Content_Cnt'].isnull()& \
    cochise['Model_Title_Cnt'].isnull()),
    cochise['category'].eq("Shotguns"),
    cochise['category'].eq("Rifles")& (cochise['Model_Content_Cnt'].notna() | \
                                             cochise['Model_Title_Cnt'].notna())
]

choices = ["Handguns", "Rifles", "Shotguns", "Assault-style Rifles"]

cochise['ET_Firearm_Type'] =  np.select(conditions, choices,default='Not_Firearm')

/Users/jasonlim/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':

In [17]:
cochise.head()

,uid,store_id,post_id,listed_date,title,category,firearm_type,County,location,action,manufacturer,caliber,registered_date,price_num,sale_type,post_content,City,State,State_id,city_lat,city_lng,state_lat,state_lng,final_lat,final_lng,extract_date,post_url,firearm_accessories,sale_buy,uid_Change,store_id_Change,category_Change,firearm_type_Change,action_Change,manufacturer_Change,caliber_Change,registered_date_Change,sale_type_Change,listed_date_Change,location_Change,price_num_Change,post_content_Change,title_Change,Model_Title_Cnt,Model_Content_Cnt,Feature_Title_Cnt,Feature_Content_Cnt,Exclude_Title_Cnt,Exclude_Content_Cnt,Model_Title,Model_Content,Feature_Title,Feature_Content,Exclude_Title,Exclude_Content,action_exclusion,Model_Title_hit,Model_Content_hit,Feature_Title_hit,Feature_Content_hit,Exclude_Title_hit,Exclude_Content_hit,UniquePostIdFlag,RecordCount,DupeRemoveFlag,uid_ChangeCount,store_id_ChangeCount,listed_date_ChangeCount,title_ChangeCount,category_ChangeCount,firearm_type_ChangeCount,location_ChangeCount,action_ChangeCount,manufacturer_ChangeCount,caliber_ChangeCount,registered_date_ChangeCount,price_num_ChangeCount,sale_type_ChangeCount,post_content_ChangeCount,data_filter,dup_filter_group,post_process,ET_Firearm_Type
19209,126613.0,NaN,7598428,2018-01-10,For Sale: Ruger 10/22,Rifles,Rifle,Cochise,"Douglas, Arizona, United States",Semi-automatic,Ruger,22 Long Rifle,NaN,300.0,Private Party,I am selling my Ruger 10/22 Tapco. Veey nice l...,Douglas,Arizona,AZ,31.60408,-109.86619,34.162819,-111.91933,31.60408,-109.86619,2018-01-10 17:15:46.240000000,http://www.armslist.com/posts/7598428,Firearms,For Sale,True,True,True,True,True,True,True,True,True,True,True,True,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.111111e+13,NaN,0.0,Rifles
22666,33452.0,NaN,7359315,2018-01-10,For Sale/Trade: Remington 700 ADL .270,Rifles,Rifle,Cochise,"Sierra Vista, Sierra Vista, Arizona",Bolt Action,Remington,270 Winchester,NaN,400.0,Private Party,Remington 700 ADLRifle comes with buttstock sl...,Sierra Vista,Arizona,AZ,31.81065,-109.99762,34.162819,-111.91933,31.81065,-109.99762,2018-01-11 02:43:12.230000000,http://www.armslist.com/posts/7359315,Firearms,For Sale,False,False,False,False,False,False,False,True,False,True,False,True,True,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,1.010110e+06,NaN,0.0,Rifles
66431,134549.0,NaN,7841354,2018-01-17,For Sale/Trade: Sig mcx patrol 5.56,Rifles,Rifle,Cochise,"Sierra Vista, Sierra Vista, Arizona",Semi-automatic,Sig Sauer,5.56×45mm NATO,2016-07-21,1500.0,Private Party,sig mcx patrol 5.56. Keymod rail. Magpul mbu...,Sierra Vista,Arizona,AZ,31.81065,-109.99762,34.162819,-111.91933,31.81065,-109.99762,2018-01-17 14:26:34.730000000,http://www.armslist.com/posts/7841354,Firearms,For Sale,True,True,True,True,True,True,True,True,True,True,True,True,True,True,1.0,1.0,NaN,NaN,NaN,NaN,MCX,MCX,NaN,NaN,NaN,NaN,N,1.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.111111e+13,NaN,0.0,Assault-style Rifles
105238,134549.0,NaN,7841342,2018-01-22,For Sale/Trade: Ruger American Predator,Rifles,Rifle,Cochise,"Sierra Vista, Sierra Vista, Arizona",Bolt Action,Ruger,308/7.62 NATO,2016-07-21,400.0,Private Party,Ruger American Predator. 308. Just the rifle....,Sierra Vista,Arizona,AZ,31.81065,-109.99762,34.162819,-111.91933,31.81065,-109.99762,2018-01-22 23:43:34.413000000,http://www.armslist.com/posts/7841342,Firearms,For Sale,True,True,True,True,True,True,True,True,True,True,True,True,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.111111e+13,NaN,0.0,Rifles
133582,146157.0,NaN,7855452,2018-01-26,For Sale: Norinco 7.62x39 sks,Rifles,Rifle,Cochise,"Sierra Vista, Sierra Vista, Arizona",Semi-automatic,Norinco,7.62x39,NaN,350.0,Private Party,norinco 7.62x39 SKS great condition shoots per...,Sierra Vista,Arizona,AZ,31.81065,-109.99762,34.162819,-111.91933,31.81065,-109.99762,2018-01-27 02:01:21.083000000,http://www.armslist.com/posts/7855452,Firearms,For Sale,True,True,True,True,True,True,True,True,True,True,True,True,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.111111e+13,NaN,0.0,Rifles

In [18]:
cochise['ET_Firearm_Type'].value_counts()

Rifles                  597
Assault-style Rifles    300
Name: ET_Firearm_Type, dtype: int64

In [19]:
cochise['Model_Title_Cnt'].value_counts()

1.0    257
2.0      7
Name: Model_Title_Cnt, dtype: int64

In [20]:
cochise['Model_Content_Cnt'].value_counts()

1.0    167
2.0     36
3.0      6
Name: Model_Content_Cnt, dtype: int64

In [21]:
len(cochise[(cochise['Model_Content_Cnt'].isnull()&cochise['Model_Title_Cnt'].isnull())])

597

In [22]:
#previously, it was following conditions. 

#conditions = [
#    final_df['category'].eq('Handguns'),
#    final_df['category'].eq("Rifles")& final_df['Model_Content_Cnt'].isnull() & \
#    final_df['Model_Title_Cnt'].isnull(),
#    final_df['category'].eq("Shotguns"),
#    final_df['category'].eq("Rifles")& (final_df['Model_Content_Cnt'].notna() | \
#                                             final_df['Model_Title_Cnt'].notna())
#]
#
#choices = ["Handguns", "Rifles", "Shotguns", "Assault-style Rifles"]
#
#final_df['ET_Firearm_Type'] =  np.select(conditions, choices,default='Not_Firearm')


final_df['category'].eq("Rifles")& final_df['Model_Content_Cnt'].isnull() &   final_df['Model_Title_Cnt'].isnull(),

There were two errors.
1. in rifle, there should be or (|) instead of and (&)
2. parenthesis was not there. 

By using these conditions, I had 
rifles : 548
assault-style Rifle : 242

Now, I have different results.

### Checking the columns that are directly from the K2 Database

1. Checking the columns that do not require any formulas from K2 Data
2. Checking the columns required formulas
3.

# C. Creating the columns

After confirmed with Kelly, we decided 3 things.

1. Create a column called category_grouping for 3 groups, Firearm, Firearm_Other, Non-Firearm.
2. Check Sale_type for Private party gun sale.
3. Like Anjali said before, I will use the following grouping for types of the firearms. <Br>
    a. Handgun - Category = 'Handgun' <br>
    b. Rifle - Category = "Rifle" AND model_title_cnt is null OR model_content_cnt is null) <br>
    c. Shotgun - Category = 'Shotgun'<br>
    d. Assault-style Rifles - category = 'Rifles' AND (model_title_cnt is not null OR model_content_cnt is not null) <Br>

In [23]:
firearm = ['Handguns', 'Rifles', 'Shotguns']
firearm_other = ['Gun Parts', 'Ammo', 'Magazines', 'Reloading', 'Antique Firearms', 'Tactical Gear', 
                 'Holsters',  'Muzzle Loaders', 'NFA Firearms', 'Gun Safes', 'Firearms Training']
non_firearm = ['Optics', 'Miscellaneous', 'Knievs', 'Archery', 'Vehicles', 'Air Guns', 
               'Targets and Range Equipment', 'Hunting Gear', 'Services', 'Events', 'Farming Equipment', 
               'Fishing Gear', 'Paintball/Airsoft', 'All Categories']

#Create a column called category_grouping for 3 groups, Firearm, Firearm_Other, Non-Firearm.

def cate_group(df):
    if df['category'] in firearm :
        return "Firearm Post"
    elif df['category'] in firearm_other:
        return "Firearm_Other Post"
    else:
        return "Non_Firearm Post"
    
    # For whole data
final_df['Category_Group'] = final_df.apply(cate_group, axis=1)

### Firearm Category

Within Firearm Post, we want to determine its types.

a. Handgun - Category = 'Handgun'

b. Rifle - Category = "Rifle" AND model_title_cnt is null AND model_content_cnt is null)

c. Shotgun - Category = 'Shotgun'

d. Assault-style Rifles - category = 'Rifles' AND (model_title_cnt is not null OR model_content_cnt is not null)

In [24]:
conditions = [
    final_df['category'].eq('Handguns'),
    final_df['category'].eq("Rifles")& (final_df['Model_Content_Cnt'].isnull()& \
    final_df['Model_Title_Cnt'].isnull()),
    final_df['category'].eq("Shotguns"),
    final_df['category'].eq("Rifles")& (final_df['Model_Content_Cnt'].notna() | \
                                             final_df['Model_Title_Cnt'].notna())
]

choices = ["Handguns", "Rifles", "Shotguns", "Assault-style Rifles"]

final_df['ET_Firearm_Type'] =  np.select(conditions, choices,default='Not_Firearm')

# illegal gun sale - without background check

it's going to depend on the state and their law. You'll want to use this google sheet as a reference (https://docs.google.com/spreadsheets/d/1HrSI25SrIMBAyvKYk7Y3yoiCvLsqcxcRuGXUmagUg8o/edit#gid=0) but i'll explain a bit more below.

1. For states where there is no background check law (column B), any firearm post listed by an unlicensed dealer (or private party) does not legally require a background check.

2. For states where there is a background check law (yes in column B) that's NOT highlighted in that pink color then all of the posts by unlicensed sellers do legally require a background check.

3. Then the states I've highlighted in that pink color are a little bit trickier because of new states passing background check laws:<br>

    a. For Nevada, if the post was by an unlicensed seller in either 2018 or 2019 then it did not legally require a check. However, starting January 2020 all posts do require a check <br>
    b. For New Mexico, posts by unlicensed sellers that were posted between January 2018 and June 2019 did not legally require a check. Posts between July 2019 and present do require a check.<br>
    c. For Virginia, posts by unlicensed sellers that were posted between January 2018 and June 2020 did not legally require a check. Posts between July 2020 and present do require a check.<br>
    d. Then for Maryland and Pennsylvania, handguns posted by unlicensed sellers do require a background check. Long guns (i.e. rifles, shotguns, and assault rifles do not.

### There are NA from sale_type which is error. These sellers should be Private Party

In [25]:
final_df['sale_type'].isna().sum()

0

In [26]:
len(final_df[final_df['sale_type'] == 'na'])

166

In [27]:
# There are na in sale_type I will replace them with Private Party

final_df['sale_type'] =final_df['sale_type'].str.replace('na', "Private Party", regex=False)

In [28]:
final_df['sale_type'].value_counts()

Private Party     7563858
Premium Vendor    1490189
Name: sale_type, dtype: int64

In [29]:
no_bg = ['Alabama','Alaska','Arizona','Arkansas','Florida','Georgia','Idaho','Indiana','Kansas','Kentucky',
         'Louisiana','Maine','Minnesota','Mississippi','Missouri','Montana','New Hampshire','North Dakota',
         'Ohio','Oklahoma','South Carolina','South Dakota','Tennessee','Texas','Utah','West Virginia',
         'Wisconsin', 'Wyoming']
yes_bg = ['California', 'Colorado','Connecticut','Delaware','District of Columbia','Hawaii','Illinois',
          'Massachusetts','New Jersey','New York','Oregon','Rhode Island',
          'Vermont','Washington']
special_state = ['Maryland', 'Nevada','New Mexico','Pennsylvania','Virginia', 'Iowa','Michigan','Nebraska',
                 'North Carolina']

# change to datetime
final_df['listed_date'] = pd.to_datetime(final_df['listed_date'])

#Create a column called category_grouping for 3 groups, Firearm, Firearm_Other, Non-Firearm.

def legal_check(df):
    # First check it is Firearm post or not
    if (df['Category_Group'] == "Firearm Post") & (df['sale_type'] =='Private Party') :
        # if state is no background check, then it is legal
        if df['State'] in no_bg :
            return "No"
        # if state is required background check, then it is illegal
        elif df['State'] in yes_bg:
            return "Yes"
        elif df['State'] in special_state:
            nv_date  = pd.to_datetime('01-01-2020').date()
            nm_date = pd.to_datetime('07-01-2019').date()
            vi_date = pd.to_datetime('07-01-2020').date()
            if (df['State']=='Nevada') & (df['listed_date']< nv_date):
                return 'No'
            elif (df['State']=='New Mexico') & (df['listed_date']< nm_date):
                return 'No'
            elif (df['State']=='Virginia') & (df['listed_date']< vi_date):
                return 'No'
            elif (df['State']=='Maryland') & (df['ET_Firearm_Type']!='Handguns'):
                return 'No'
            elif (df['State']=='Pennsylvania') & (df['ET_Firearm_Type']!='Handguns'):
                return 'No'
            elif (df['State']=='Iowa') & (df['ET_Firearm_Type']!='Handguns'):
                return 'No'
            elif (df['State']=='Michigan') & (df['ET_Firearm_Type']!='Handguns'):
                return 'No'
            elif (df['State']=='Nebraska') & (df['ET_Firearm_Type']!='Handguns'):
                return 'No'
            elif (df['State']=='North Carolina') & (df['ET_Firearm_Type']!='Handguns'):
                return 'No'
            else:
                return 'Yes'
    elif (df['Category_Group'] == "Firearm Post") & (df['sale_type'] =='Premium Vendor') :
        return 'Yes'
    else:
        return "Not_Firearm_Post"
    
    

final_df['Background_Check']= final_df.apply(legal_check, axis=1)

In [30]:
final_df.head()

,uid,store_id,post_id,listed_date,title,category,firearm_type,County,location,action,manufacturer,caliber,registered_date,price_num,sale_type,post_content,City,State,State_id,city_lat,city_lng,state_lat,state_lng,final_lat,final_lng,extract_date,post_url,firearm_accessories,sale_buy,uid_Change,store_id_Change,category_Change,firearm_type_Change,action_Change,manufacturer_Change,caliber_Change,registered_date_Change,sale_type_Change,listed_date_Change,location_Change,price_num_Change,post_content_Change,title_Change,Model_Title_Cnt,Model_Content_Cnt,Feature_Title_Cnt,Feature_Content_Cnt,Exclude_Title_Cnt,Exclude_Content_Cnt,Model_Title,Model_Content,Feature_Title,Feature_Content,Exclude_Title,Exclude_Content,action_exclusion,Model_Title_hit,Model_Content_hit,Feature_Title_hit,Feature_Content_hit,Exclude_Title_hit,Exclude_Content_hit,UniquePostIdFlag,RecordCount,DupeRemoveFlag,uid_ChangeCount,store_id_ChangeCount,listed_date_ChangeCount,title_ChangeCount,category_ChangeCount,firearm_type_ChangeCount,location_ChangeCount,action_ChangeCount,manufacturer_ChangeCount,caliber_ChangeCount,registered_date_ChangeCount,price_num_ChangeCount,sale_type_ChangeCount,post_content_ChangeCount,data_filter,dup_filter_group,post_process,Category_Group,ET_Firearm_Type,Background_Check
0,116028.0,NaN,7769732,2018-01-07,For Sale: Small Collection of German Handguns.,Handguns,Pistol,Greene,"SPFD, Springfield, Missouri",NaN,NaN,NaN,NaN,1.0,Private Party,Small Collection of German Handguns. 7 Lugers ...,Springfield,Missouri,MO,37.258072,-93.343674,38.310318,-92.421555,37.258072,-93.343674,2018-01-07 16:03:34.680000000,http://www.armslist.com/posts/7769732,Firearms,For Sale,False,False,False,False,False,False,False,False,False,True,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.000000e+04,K2,0.0,Firearm Post,Handguns,No
1,115037.0,NaN,7767216,2018-01-07,For Sale/Trade: 300AAC AR15 Pistol Upper,Handguns,Pistol,Madison,"Huntsville, Huntsville, Alabama",Single Action,Anderson Manufacturing,NaN,2014-02-09,400.0,Private Party,"300AAC AR15 Pistol Upper:ALG 10"" RailNoveske K...",Huntsville,Alabama,AL,34.733963,-86.522911,32.609589,-86.729843,34.733963,-86.522911,2018-01-07 16:03:35.987000000,http://www.armslist.com/posts/7767216,Firearms,For Sale,True,True,True,True,True,True,True,True,True,True,True,True,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.111111e+13,NaN,0.0,Firearm Post,Handguns,No
2,115037.0,NaN,7767236,2018-01-07,For Sale: S&W Model 36-10 Revolver,Handguns,Revolver,Madison,"Huntsville, Huntsville, Alabama",Double / Single Action,Smith & Wesson,38 S&W Special,2014-02-09,550.0,Private Party,S&W Model 36-10 RevolverPurchased new Summer 2...,Huntsville,Alabama,AL,34.733963,-86.522911,32.609589,-86.729843,34.733963,-86.522911,2018-01-07 16:03:36.943000000,http://www.armslist.com/posts/7767236,Firearms,For Sale,False,False,False,False,False,False,False,False,False,True,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000e+04,K2,0.0,Firearm Post,Handguns,No
3,99474.0,NaN,7772635,2018-01-07,For Sale: Glock 19 Gen 4 with front serrations,Handguns,Pistol,Hillsborough,"Dover, Tampa/St. Pete, Florida",Striker Fire,Glock,9mm Luger (9x19),2017-07-25,550.0,Private Party,LNIB. Has front serrations from factory. Pol...,Dover,Florida,FL,27.975742,-82.240417,27.771553,-83.772789,27.975742,-82.240417,2018-01-07 16:03:37.730000000,http://www.armslist.com/posts/7772635,Firearms,For Sale,True,True,True,True,True,True,True,True,True,True,True,True,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.111111e+13,NaN,0.0,Firearm Post,Handguns,No
4,3319.0,NaN,6640627,2018-01-07,For Sale: SW 625JM,Handguns,Revolver,San Francisco,"Martinez, San Francisco, California",Double / Single Action,Smith & Wesson,45 ACP,2015-07-08,800.0,Private Party,I have a smith and wesson model 625 JM for sal...,San Francisco,California,CA,37.784828,-122.727800,37.286072,-119.279170,37.784828,-122.727800,2018-01-07 16:03:38.520000000,http://www.armslist.com/posts/6640627,Firearms,For Sale,False,False,False,False,False,False,False,False,False,True,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000e+04,K2,0.0,Firearm Post,Handguns,Yes

### Columns from Unchecked full dataset and its Sources


Columns | Sources (Formula/K2)
-- | --
uid | K2
store_id | K2
post_id | K2
listed_date | K2
category | Formula
firearm_type | K2
county | K2
sale_type | K2
state | K2
state_id | K2
final_lat | Formula
final_lng | Formula
sale_buy | K2
background_check | Formula
state_bgc_law | Formula
state_pop | Census
county_pop | Census

I already distinguish Category, Background_check, and State_bgc_law. <br>
Other parts that I will continue to do are:
1. population for state and County
2. lat and long --> will figure out in the Tableau

In [32]:
# Removing Duperemoveflag ==1 and not firearm 

final_df2 = final_df[(final_df['DupeRemoveFlag']!=1) &
                    (final_df['ET_Firearm_Type']!="Not_Firearm") &
                    (final_df['State'] != 'Puerto Rico')&
                    (final_df['State'] != 'Guam')]

In [33]:
len(final_df2)

6390905

In [34]:
final_df2.head()

,uid,store_id,post_id,listed_date,title,category,firearm_type,County,location,action,manufacturer,caliber,registered_date,price_num,sale_type,post_content,City,State,State_id,city_lat,city_lng,state_lat,state_lng,final_lat,final_lng,extract_date,post_url,firearm_accessories,sale_buy,uid_Change,store_id_Change,category_Change,firearm_type_Change,action_Change,manufacturer_Change,caliber_Change,registered_date_Change,sale_type_Change,listed_date_Change,location_Change,price_num_Change,post_content_Change,title_Change,Model_Title_Cnt,Model_Content_Cnt,Feature_Title_Cnt,Feature_Content_Cnt,Exclude_Title_Cnt,Exclude_Content_Cnt,Model_Title,Model_Content,Feature_Title,Feature_Content,Exclude_Title,Exclude_Content,action_exclusion,Model_Title_hit,Model_Content_hit,Feature_Title_hit,Feature_Content_hit,Exclude_Title_hit,Exclude_Content_hit,UniquePostIdFlag,RecordCount,DupeRemoveFlag,uid_ChangeCount,store_id_ChangeCount,listed_date_ChangeCount,title_ChangeCount,category_ChangeCount,firearm_type_ChangeCount,location_ChangeCount,action_ChangeCount,manufacturer_ChangeCount,caliber_ChangeCount,registered_date_ChangeCount,price_num_ChangeCount,sale_type_ChangeCount,post_content_ChangeCount,data_filter,dup_filter_group,post_process,Category_Group,ET_Firearm_Type,Background_Check
0,116028.0,NaN,7769732,2018-01-07,For Sale: Small Collection of German Handguns.,Handguns,Pistol,Greene,"SPFD, Springfield, Missouri",NaN,NaN,NaN,NaN,1.0,Private Party,Small Collection of German Handguns. 7 Lugers ...,Springfield,Missouri,MO,37.258072,-93.343674,38.310318,-92.421555,37.258072,-93.343674,2018-01-07 16:03:34.680000000,http://www.armslist.com/posts/7769732,Firearms,For Sale,False,False,False,False,False,False,False,False,False,True,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.000000e+04,K2,0.0,Firearm Post,Handguns,No
1,115037.0,NaN,7767216,2018-01-07,For Sale/Trade: 300AAC AR15 Pistol Upper,Handguns,Pistol,Madison,"Huntsville, Huntsville, Alabama",Single Action,Anderson Manufacturing,NaN,2014-02-09,400.0,Private Party,"300AAC AR15 Pistol Upper:ALG 10"" RailNoveske K...",Huntsville,Alabama,AL,34.733963,-86.522911,32.609589,-86.729843,34.733963,-86.522911,2018-01-07 16:03:35.987000000,http://www.armslist.com/posts/7767216,Firearms,For Sale,True,True,True,True,True,True,True,True,True,True,True,True,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.111111e+13,NaN,0.0,Firearm Post,Handguns,No
2,115037.0,NaN,7767236,2018-01-07,For Sale: S&W Model 36-10 Revolver,Handguns,Revolver,Madison,"Huntsville, Huntsville, Alabama",Double / Single Action,Smith & Wesson,38 S&W Special,2014-02-09,550.0,Private Party,S&W Model 36-10 RevolverPurchased new Summer 2...,Huntsville,Alabama,AL,34.733963,-86.522911,32.609589,-86.729843,34.733963,-86.522911,2018-01-07 16:03:36.943000000,http://www.armslist.com/posts/7767236,Firearms,For Sale,False,False,False,False,False,False,False,False,False,True,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000e+04,K2,0.0,Firearm Post,Handguns,No
3,99474.0,NaN,7772635,2018-01-07,For Sale: Glock 19 Gen 4 with front serrations,Handguns,Pistol,Hillsborough,"Dover, Tampa/St. Pete, Florida",Striker Fire,Glock,9mm Luger (9x19),2017-07-25,550.0,Private Party,LNIB. Has front serrations from factory. Pol...,Dover,Florida,FL,27.975742,-82.240417,27.771553,-83.772789,27.975742,-82.240417,2018-01-07 16:03:37.730000000,http://www.armslist.com/posts/7772635,Firearms,For Sale,True,True,True,True,True,True,True,True,True,True,True,True,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.111111e+13,NaN,0.0,Firearm Post,Handguns,No
4,3319.0,NaN,6640627,2018-01-07,For Sale: SW 625JM,Handguns,Revolver,San Francisco,"Martinez, San Francisco, California",Double / Single Action,Smith & Wesson,45 ACP,2015-07-08,800.0,Private Party,I have a smith and wesson model 625 JM for sal...,San Francisco,California,CA,37.784828,-122.727800,37.286072,-119.279170,37.784828,-122.727800,2018-01-07 16:03:38.520000000,http://www.armslist.com/posts/6640627,Firearms,For Sale,False,False,False,False,False,False,False,False,False,True,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000e+04,K2,0.0,Firearm Post,Handguns,Yes

### Adding Anjali rule.
-update research.onlinesales_full_dataset_bgc_20190111
set county = 'St. Louis'
where county = 'St. Louis (city)'
and state = 'Missouri'
and city != 'Saint Louis';


-update research.onlinesales_full_dataset_bgc_20190111
set county = 'Baltimore (city)'
where county = 'Baltimore'
and state = 'Maryland'
and city = 'Baltimore';

-update research.onlinesales_full_dataset_bgc_20190111
set county = 'Baltimore (city)' where county = 'Baltimore city';

-update research.onlinesales_full_dataset_bgc_20190111
set county = 'Saint Francois'
where county = 'St. Francois' and state = 'Missouri'

In [35]:
def anjali_rule(df):
    # St.Louis
    if df['State']=='Missouri' and df['County']=='St. Louis (city)' and df['City'] != 'Saint Louis':
        return 'St. Louis'
    # Baltimore City
    elif df['State'] == 'Maryland' and df['County']=='Baltimore' and df['City'] == 'Baltimore':
        return 'Baltimore city'
    elif df['State'] == 'Missouri' and df['County']=='St. Francois':
        return 'Saint Francois'
    else:
        return df['County']

In [36]:
# apply the rule
final_df2['County'] = final_df2.apply(anjali_rule, axis=1)

/Users/jasonlim/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

# 1. AGG. County level

### Combining with population Dataset

The population dataset is from the Census's most recent dataset.
https://www2.census.gov/programs-surveys/popest/datasets/2010-2019/cities/totals/

After I downloaded sub-est2019_all.csv file, which is a combined dataset of Subcounty Resident Population Estimates: April 1, 2010 to July 1, 2019

The description is in the following webpage,
https://www2.census.gov/programs-surveys/popest/technical-documentation/file-layouts/2010-2019/sub-est2019.pdf.

From this file, I will pull out the following parts,

1. County population of 2018-2019, SUMLEV = 50

In [37]:


g = final_df2.groupby(['ET_Firearm_Type', 'County','State','Background_Check','sale_type', 'sale_buy'], dropna=False)['post_id']

m =g.count().reset_index().sort_values( 'post_id', ascending=False)
m.rename(columns={"post_id": "total_#_post_id"}, inplace=True)

m['County'] = m['County'].fillna('Undetermined')

In [38]:
# creating the function 

#law


def county_join_name(df):
    # St.Louis (City)
    if "(city)" in df['County']:
        return df['County'].replace("(city)", "city")
    elif "city" in df['County']:
        return df['County']
    elif "County" in df['County']:
        return df['County']
    
    elif "City and" in df ['County']:
        return df['County'].replace("City and", "City and Borough")
    elif "City" in df ['County']:
        return df['County'].replace("City", "city")
    elif "Saint" in df['County']:
        return df['County'].replace("Saint", "St.")+' County'
    else: 
        return df['County']+' County'
    
    
    
    
# apply the rule
m['County_join'] = m.apply(county_join_name, axis=1)

#### 1a. Pull out County population dataset

In [39]:
pop = pd.read_csv("County_Pop/sub-est2019_all.csv", encoding='latin-1')



# filter only county, which is SUMLEV == 50

county_pop = pop[pop['SUMLEV']==50]

county_pop.head()

,SUMLEV,STATE,COUNTY,PLACE,COUSUB,CONCIT,PRIMGEO_FLAG,FUNCSTAT,NAME,STNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,POPESTIMATE2013,POPESTIMATE2014,POPESTIMATE2015,POPESTIMATE2016,POPESTIMATE2017,POPESTIMATE2018,POPESTIMATE2019
463,50,1,1,0,0,0,0,A,Autauga County,Alabama,54571,54597,54773,55227,54954,54727,54893,54864,55243,55390,55533,55869
469,50,1,3,0,0,0,0,A,Baldwin County,Alabama,182265,182265,183112,186558,190145,194885,199183,202939,207601,212521,217855,223234
485,50,1,5,0,0,0,0,A,Barbour County,Alabama,27457,27455,27327,27341,27169,26937,26755,26283,25806,25157,24872,24686
493,50,1,7,0,0,0,0,A,Bibb County,Alabama,22915,22915,22870,22745,22667,22521,22553,22566,22586,22550,22367,22394
500,50,1,9,0,0,0,0,A,Blount County,Alabama,57322,57322,57376,57560,57580,57619,57526,57526,57494,57787,57771,57826

In [40]:
county_pop.columns

Index(['SUMLEV', 'STATE', 'COUNTY', 'PLACE', 'COUSUB', 'CONCIT',
       'PRIMGEO_FLAG', 'FUNCSTAT', 'NAME', 'STNAME', 'CENSUS2010POP',
       'ESTIMATESBASE2010', 'POPESTIMATE2010', 'POPESTIMATE2011',
       'POPESTIMATE2012', 'POPESTIMATE2013', 'POPESTIMATE2014',
       'POPESTIMATE2015', 'POPESTIMATE2016', 'POPESTIMATE2017',
       'POPESTIMATE2018', 'POPESTIMATE2019'],
      dtype='object')

In [41]:
# special Char city
    
county_pop['NAME'] = county_pop['NAME'].str.replace('Doña Ana County', 'Dona Ana County')

/Users/jasonlim/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [42]:
county_pop[county_pop['NAME']=='Dona Ana County']

,SUMLEV,STATE,COUNTY,PLACE,COUSUB,CONCIT,PRIMGEO_FLAG,FUNCSTAT,NAME,STNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,POPESTIMATE2013,POPESTIMATE2014,POPESTIMATE2015,POPESTIMATE2016,POPESTIMATE2017,POPESTIMATE2018,POPESTIMATE2019
46079,50,35,13,0,0,0,0,A,Dona Ana County,New Mexico,209233,209217,210097,213126,214450,214288,213933,214034,214663,216174,217278,218195

In [43]:
# filter only 2018 and 2019

c_pop = county_pop[['NAME', 'STNAME','POPESTIMATE2018','POPESTIMATE2019']]

# create 2020 with 2019 database
c_pop['POPESTIMATE2020'] = c_pop['POPESTIMATE2019']

# Making all upper case
c_pop['STNAME_Upper'] = c_pop['STNAME'].astype(str).str.upper()
c_pop['NAME_Upper'] = c_pop['NAME'].astype(str).str.upper()

# same for m
m['County_Upper'] = m['County_join'].astype(str).str.upper()
m['State_Upper'] = m['State'].astype(str).str.upper()

/Users/jasonlim/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/Users/jasonlim/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/Users/jasonlim/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

***WARNING ***For Alaska, Special Case: for Alaska, there are different names such as (Census Area, City and Borough). So, just for Alaska, I will remove these name and purely use city name to join

In [44]:
c_pop1= c_pop[c_pop['STNAME']!='Alaska']
al_df = c_pop[c_pop['STNAME']=='Alaska']

# seems like Alaska has too many different words, so just for Alaska I will take out unnessary word and join


pattern = '|'.join([' city', ' town', ' County', ' township', ' municipality', ' Borough', 
                    ' Area', ' city and borough', ' CENSUS', " AND"])

al_df['NAME_Upper'] = al_df['NAME_Upper'].str.replace(pattern, "", regex=True, flags=re.IGNORECASE)

result_df = pd.concat([c_pop1, al_df])

/Users/jasonlim/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

In [45]:
m1= m[m['State']!='Alaska']
m_al_df = m[m['State']=='Alaska']

# seems like Alaska has too many different words, so just for Alaska I will take out unnessary word and join


pattern = '|'.join([' city', ' town', ' County', ' township', ' municipality', ' Borough', 
                    ' Area', ' city and borough', ' CENSUS', " and"])

m_al_df['County_Upper'] = m_al_df['County_Upper'].str.replace(pattern, "", regex=True, flags=re.IGNORECASE)

result_m = pd.concat([m1, m_al_df])

/Users/jasonlim/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

In [46]:
# joining
new_df4 = result_df.merge(result_m,how='outer', left_on=['STNAME_Upper', 'NAME_Upper'], right_on=['State_Upper', 'County_Upper'])

In [47]:
# Checking total post numbers
new_df4['total_#_post_id'].sum()

6390905.0

In [48]:
# Sample Check
new_df4[new_df4['NAME']=='Acadia Parish']

,NAME,STNAME,POPESTIMATE2018,POPESTIMATE2019,POPESTIMATE2020,STNAME_Upper,NAME_Upper,ET_Firearm_Type,County,State,Background_Check,sale_type,sale_buy,total_#_post_id,County_join,County_Upper,State_Upper
6711,Acadia Parish,Louisiana,62214.0,62045.0,62045.0,LOUISIANA,ACADIA PARISH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [49]:
new_df4[new_df4['NAME']=='Doña Ana County']

Empty DataFrame
Columns: [NAME, STNAME, POPESTIMATE2018, POPESTIMATE2019, POPESTIMATE2020, STNAME_Upper, NAME_Upper, ET_Firearm_Type, County, State, Background_Check, sale_type, sale_buy, total_#_post_id, County_join, County_Upper, State_Upper]
Index: []

#### 1b. Creating Dummy Rows

In [50]:
# create separate df for Sale_buy and ET_firearm type and sale_type
# even I use outer join for 

# 1. separate null of total#

null_df = new_df4[new_df4['total_#_post_id'].isnull()]




# Firearm type 
null_df['ET_Firearm_Type']="Handguns,Rifles,Assault-style Rifles,Shotguns"


# convert to list
null_df['ET_Firearm_Type'] = null_df['ET_Firearm_Type'].str.split(',')


# convert list of pd.Series then stack it
null_df = (null_df
 .set_index(['NAME','STNAME','NAME_Upper','STNAME_Upper','POPESTIMATE2018','POPESTIMATE2019', 'POPESTIMATE2020','total_#_post_id'])['ET_Firearm_Type']
 .apply(pd.Series)
 .stack()
 .reset_index()
 .rename(columns={0:'ET_Firearm_Type'}))


null_df['sale_type'] = "Private Party,Premium Vendor"

null_df['sale_type'] = null_df['sale_type'].str.split(',')

null_df = (null_df
 .set_index(['NAME','STNAME','NAME_Upper','STNAME_Upper','POPESTIMATE2018','POPESTIMATE2019', 'POPESTIMATE2020','total_#_post_id','ET_Firearm_Type'])['sale_type']
 .apply(pd.Series)
 .stack()
 .reset_index()
 .rename(columns={0:'sale_type'}))




null_df['sale_buy'] = "Want to Buy,For Sale,For Trade"



null_df['sale_buy'] = null_df['sale_buy'].str.split(',')

null_df = (null_df
 .set_index(['NAME','STNAME','NAME_Upper','STNAME_Upper','POPESTIMATE2018','POPESTIMATE2019', 'POPESTIMATE2020','total_#_post_id','ET_Firearm_Type','sale_type'])['sale_buy']
 .apply(pd.Series)
 .stack()
 .reset_index()
 .rename(columns={0:'sale_buy'}))

/Users/jasonlim/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':
/Users/jasonlim/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()

In [51]:
null_df.head()

,NAME,STNAME,NAME_Upper,STNAME_Upper,POPESTIMATE2018,POPESTIMATE2019,POPESTIMATE2020,total_#_post_id,ET_Firearm_Type,sale_type,level_10,sale_buy
0,Bullock County,Alabama,BULLOCK COUNTY,ALABAMA,10174.0,10101.0,10101.0,NaN,Handguns,Private Party,0,Want to Buy
1,Bullock County,Alabama,BULLOCK COUNTY,ALABAMA,10174.0,10101.0,10101.0,NaN,Handguns,Private Party,1,For Sale
2,Bullock County,Alabama,BULLOCK COUNTY,ALABAMA,10174.0,10101.0,10101.0,NaN,Handguns,Private Party,2,For Trade
3,Bullock County,Alabama,BULLOCK COUNTY,ALABAMA,10174.0,10101.0,10101.0,NaN,Handguns,Premium Vendor,0,Want to Buy
4,Bullock County,Alabama,BULLOCK COUNTY,ALABAMA,10174.0,10101.0,10101.0,NaN,Handguns,Premium Vendor,1,For Sale

In [52]:
null_df=null_df.drop('level_10', axis=1)

In [53]:
# pull out notnull df and append with null_Df with dummy rows

not_null_df = new_df4[new_df4['total_#_post_id'].notnull()]

new_df_final = not_null_df.append(null_df, sort=False)

In [54]:
new_df_final['NAME'].nunique()

1877

In [55]:

new_df_final = new_df_final[['NAME', 'STNAME', 'POPESTIMATE2018','POPESTIMATE2019', 'POPESTIMATE2020',
                             'ET_Firearm_Type', 'County', 'State', 
                             'Background_Check', 'sale_type','sale_buy', 'total_#_post_id']]

In [56]:
new_df_final['total_#_post_id'].sum()

6390905.0

In [57]:
# create population columns
new_df_final['population_3_years_sum'] = new_df_final['POPESTIMATE2018']+new_df_final['POPESTIMATE2019']+new_df_final['POPESTIMATE2020']

In [58]:
new_df_final.head()

,NAME,STNAME,POPESTIMATE2018,POPESTIMATE2019,POPESTIMATE2020,ET_Firearm_Type,County,State,Background_Check,sale_type,sale_buy,total_#_post_id,population_3_years_sum
0,Autauga County,Alabama,55533.0,55869.0,55869.0,Rifles,Autauga,Alabama,Yes,Premium Vendor,For Sale,566.0,167271.0
1,Autauga County,Alabama,55533.0,55869.0,55869.0,Assault-style Rifles,Autauga,Alabama,Yes,Premium Vendor,For Sale,350.0,167271.0
2,Autauga County,Alabama,55533.0,55869.0,55869.0,Handguns,Autauga,Alabama,Yes,Premium Vendor,For Sale,120.0,167271.0
3,Autauga County,Alabama,55533.0,55869.0,55869.0,Handguns,Autauga,Alabama,No,Private Party,For Sale,22.0,167271.0
4,Autauga County,Alabama,55533.0,55869.0,55869.0,Assault-style Rifles,Autauga,Alabama,No,Private Party,For Sale,8.0,167271.0

In [59]:
#new_df_final.to_csv('County_agg_result.csv', index=False)

# 2. AGG. State level with Year and population

Establishing State level dataset with State population and month level for Trend

In [60]:

# Month Post

per = final_df2.listed_date.dt.to_period("Y") 
g = final_df2.groupby(['ET_Firearm_Type', 'County','State',per,'Background_Check','sale_type', 'sale_buy'], dropna=False)['post_id']

m =g.count().reset_index().sort_values(['listed_date', 'post_id'], ascending=[True, False])

m.rename(columns={"post_id": "total_#_post_id"}, inplace=True)

m['County'] = m['County'].fillna('Undetermined')

In [61]:
m['total_#_post_id'].sum()

6390905

In [62]:
m.head()

,ET_Firearm_Type,County,State,listed_date,Background_Check,sale_type,sale_buy,total_#_post_id
16160,Handguns,Maricopa,Arizona,2018,No,Private Party,For Sale,21523
14019,Handguns,Hillsborough,Florida,2018,No,Private Party,For Sale,18781
17628,Handguns,Oklahoma,Oklahoma,2018,No,Private Party,For Sale,15865
12894,Handguns,Franklin,Ohio,2018,No,Private Party,For Sale,15487
15068,Handguns,Knox,Tennessee,2018,No,Private Party,For Sale,14746

### 2a. State population Dataset

I will use the Census State population estimate and household estimate for each state.
We already set up this file in the following location.
https://github.com/everytown/research-reference-state/tree/master/Household

sumlev = 40

In [63]:
pop.head()

,SUMLEV,STATE,COUNTY,PLACE,COUSUB,CONCIT,PRIMGEO_FLAG,FUNCSTAT,NAME,STNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,POPESTIMATE2013,POPESTIMATE2014,POPESTIMATE2015,POPESTIMATE2016,POPESTIMATE2017,POPESTIMATE2018,POPESTIMATE2019
0,40,1,0,0,0,0,0,A,Alabama,Alabama,4779736,4780125,4785437,4799069,4815588,4830081,4841799,4852347,4863525,4874486,4887681,4903185
1,162,1,0,124,0,0,0,A,Abbeville city,Alabama,2688,2705,2699,2694,2643,2628,2608,2600,2584,2575,2571,2560
2,162,1,0,460,0,0,0,A,Adamsville city,Alabama,4522,4506,4500,4493,4471,4449,4420,4390,4356,4327,4308,4281
3,162,1,0,484,0,0,0,A,Addison town,Alabama,758,754,751,750,743,742,739,734,731,726,723,718
4,162,1,0,676,0,0,0,A,Akron town,Alabama,356,356,355,347,347,343,338,339,333,332,331,328

In [64]:
# filter only county, which is SUMLEV == 40

pop = pd.read_csv("County_Pop/sub-est2019_all.csv", encoding='latin-1')



# filter only county, which is SUMLEV == 40

state_pop = pop[pop['SUMLEV']==40]

state_pop.head()

,SUMLEV,STATE,COUNTY,PLACE,COUSUB,CONCIT,PRIMGEO_FLAG,FUNCSTAT,NAME,STNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,POPESTIMATE2013,POPESTIMATE2014,POPESTIMATE2015,POPESTIMATE2016,POPESTIMATE2017,POPESTIMATE2018,POPESTIMATE2019
0,40,1,0,0,0,0,0,A,Alabama,Alabama,4779736,4780125,4785437,4799069,4815588,4830081,4841799,4852347,4863525,4874486,4887681,4903185
1108,40,2,0,0,0,0,0,A,Alaska,Alaska,710231,710249,713910,722128,730443,737068,736283,737498,741456,739700,735139,731545
1457,40,4,0,0,0,0,0,A,Arizona,Arizona,6392017,6392288,6407172,6472643,6554978,6632764,6730413,6829676,6941072,7044008,7158024,7278717
1678,40,5,0,0,0,0,0,A,Arkansas,Arkansas,2915918,2916031,2921964,2940667,2952164,2959400,2967392,2978048,2989918,3001345,3009733,3017804
2851,40,6,0,0,0,0,0,A,California,California,37253956,37254519,37319502,37638369,37948800,38260787,38596972,38918045,39167117,39358497,39461588,39512223

In [65]:
s_pop = state_pop[['NAME', 'STNAME','POPESTIMATE2018','POPESTIMATE2019']]

s_pop.head()

            NAME      STNAME  POPESTIMATE2018  POPESTIMATE2019
0        Alabama     Alabama          4887681          4903185
1108      Alaska      Alaska           735139           731545
1457     Arizona     Arizona          7158024          7278717
1678    Arkansas    Arkansas          3009733          3017804
2851  California  California         39461588         39512223

In [66]:
# create 2020 with 2019 database
s_pop['POPESTIMATE2020'] =s_pop['POPESTIMATE2019']

/Users/jasonlim/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [67]:
s_pop.head()

,NAME,STNAME,POPESTIMATE2018,POPESTIMATE2019,POPESTIMATE2020
0,Alabama,Alabama,4887681,4903185,4903185
1108,Alaska,Alaska,735139,731545,731545
1457,Arizona,Arizona,7158024,7278717,7278717
1678,Arkansas,Arkansas,3009733,3017804,3017804
2851,California,California,39461588,39512223,39512223

In [68]:
# pivot table into join df form
s_pop_18_20 = s_pop.melt(id_vars=["NAME", "STNAME"], 
        var_name="YEAR", 
        value_name="State_POPULATION")

s_pop_18_20['YEAR'] = s_pop_18_20['YEAR'].astype(str).str[-4:]

In [69]:
s_pop_18_20.tail()

              NAME         STNAME  YEAR  State_POPULATION
148       Virginia       Virginia  2020           8535519
149     Washington     Washington  2020           7614893
150  West Virginia  West Virginia  2020           1792147
151      Wisconsin      Wisconsin  2020           5822434
152        Wyoming        Wyoming  2020            578759

In [70]:
m.columns

Index(['ET_Firearm_Type', 'County', 'State', 'listed_date', 'Background_Check',
       'sale_type', 'sale_buy', 'total_#_post_id'],
      dtype='object')

In [71]:
m.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 43132 entries, 16160 to 43131
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ET_Firearm_Type   43132 non-null  object
 1   County            43132 non-null  object
 2   State             43111 non-null  object
 3   listed_date       43132 non-null  period[A-DEC]
 4   Background_Check  43111 non-null  object
 5   sale_type         43132 non-null  object
 6   sale_buy          43124 non-null  object
 7   total_#_post_id   43132 non-null  int64
dtypes: int64(1), object(6), period[A-DEC](1)
memory usage: 3.0+ MB

In [72]:
s_pop_18_20.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 153 entries, 0 to 152
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   NAME              153 non-null    object
 1   STNAME            153 non-null    object
 2   YEAR              153 non-null    object
 3   State_POPULATION  153 non-null    int64
dtypes: int64(1), object(3)
memory usage: 4.9+ KB

In [73]:
# Create year column in state df, so we can join with pop df easily
m.rename(columns={'listed_date':'YEAR'}, inplace=True)

In [74]:


m['YEAR'] = m['YEAR'].astype(str)

In [75]:
m.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 43132 entries, 16160 to 43131
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ET_Firearm_Type   43132 non-null  object
 1   County            43132 non-null  object
 2   State             43111 non-null  object
 3   YEAR              43132 non-null  object
 4   Background_Check  43111 non-null  object
 5   sale_type         43132 non-null  object
 6   sale_buy          43124 non-null  object
 7   total_#_post_id   43132 non-null  int64
dtypes: int64(1), object(7)
memory usage: 3.0+ MB

In [76]:
# combine with state dataset 
state_df = m.merge(s_pop_18_20, how='left', left_on=['State', 'YEAR'], right_on=['NAME', 'YEAR'])

In [77]:
# Confirming null rows, which should be none
state_df[state_df['total_#_post_id'].isnull()]

Empty DataFrame
Columns: [ET_Firearm_Type, County, State, YEAR, Background_Check, sale_type, sale_buy, total_#_post_id, NAME, STNAME, State_POPULATION]
Index: []

In [78]:
state_df['total_#_post_id'].sum()

6390905

In [79]:
state_df.columns

Index(['ET_Firearm_Type', 'County', 'State', 'YEAR', 'Background_Check',
       'sale_type', 'sale_buy', 'total_#_post_id', 'NAME', 'STNAME',
       'State_POPULATION'],
      dtype='object')

In [80]:
# erase duplicate and unuseful columns

state_df = state_df[['ET_Firearm_Type', 'County', 'State', 'YEAR', 'Background_Check',
       'sale_type', 'sale_buy', 'total_#_post_id', 'State_POPULATION']]

### 2b. County population for every year

In [81]:
# creating the function 

#law


def county_join_name(df):
    # St.Louis (City)
    if "(city)" in df['County']:
        return df['County'].replace("(city)", "city")
    elif "city" in df['County']:
        return df['County']
    elif "County" in df['County']:
        return df['County']
    
    elif "City and" in df ['County']:
        return df['County'].replace("City and", "City and Borough")
    elif "City" in df ['County']:
        return df['County'].replace("City", "city")
    elif "Saint" in df['County']:
        return df['County'].replace("Saint", "St.")+' County'
    else: 
        return df['County']+' County'
    
    
    
    
# apply the rule
state_df['County_join'] = state_df.apply(county_join_name, axis=1)

In [82]:
state_df.head()

,ET_Firearm_Type,County,State,YEAR,Background_Check,sale_type,sale_buy,total_#_post_id,State_POPULATION,County_join
0,Handguns,Maricopa,Arizona,2018,No,Private Party,For Sale,21523,7158024.0,Maricopa County
1,Handguns,Hillsborough,Florida,2018,No,Private Party,For Sale,18781,21244317.0,Hillsborough County
2,Handguns,Oklahoma,Oklahoma,2018,No,Private Party,For Sale,15865,3940235.0,Oklahoma County
3,Handguns,Franklin,Ohio,2018,No,Private Party,For Sale,15487,11676341.0,Franklin County
4,Handguns,Knox,Tennessee,2018,No,Private Party,For Sale,14746,6771631.0,Knox County

In [83]:
# for 2018 and 2019
c_pop = county_pop[['NAME', 'STNAME','POPESTIMATE2018','POPESTIMATE2019']]
# create Year 2020
# I will use Year 2019 for 2020 as well.

c_pop['POPESTIMATE2020'] = c_pop['POPESTIMATE2019']



# pivot table into join df form
c_pop_18_20 = c_pop.melt(id_vars=["NAME", "STNAME"], 
        var_name="YEAR", 
        value_name="COUNTY_POPULATION")


# erase text from year
c_pop_18_20['YEAR'] = c_pop_18_20['YEAR'].astype(str).str[-4:].astype(int)

/Users/jasonlim/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [84]:
c_pop_18_20.tail()

                   NAME   STNAME  YEAR  COUNTY_POPULATION
9421  Sweetwater County  Wyoming  2020              42343
9422       Teton County  Wyoming  2020              23464
9423       Uinta County  Wyoming  2020              20226
9424    Washakie County  Wyoming  2020               7805
9425      Weston County  Wyoming  2020               6927

In [85]:
len(c_pop_18_20)

9426

In [86]:

# Making all upper case
c_pop_18_20['STNAME_Upper'] = c_pop_18_20['STNAME'].astype(str).str.upper()
c_pop_18_20['NAME_Upper'] = c_pop_18_20['NAME'].astype(str).str.upper()

# same for m
state_df['County_Upper'] = state_df['County_join'].astype(str).str.upper()
state_df['State_Upper'] = state_df['State'].astype(str).str.upper()

#### For Alaska, I implemented the same rule.

In [87]:
c_pop2= c_pop_18_20[c_pop_18_20['STNAME']!='Alaska']
al_df2 = c_pop_18_20[c_pop_18_20['STNAME']=='Alaska']

# seems like Alaska has too many different words, so just for Alaska I will take out unnessary word and join


pattern = '|'.join([' city', ' town', ' County', ' township', ' municipality', ' Borough', 
                    ' Area', ' city and borough', ' CENSUS', " AND"])

al_df2['NAME_Upper'] = al_df2['NAME_Upper'].str.replace(pattern, "", regex=True, flags=re.IGNORECASE)

result_df2 = pd.concat([c_pop2, al_df2])

/Users/jasonlim/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

In [88]:
m2= state_df[state_df['State']!='Alaska']
m2_al_df = state_df[state_df['State']=='Alaska']

# seems like Alaska has too many different words, so just for Alaska I will take out unnessary word and join


pattern = '|'.join([' city', ' town', ' County', ' township', ' municipality', ' Borough', 
                    ' Area', ' city and borough', ' CENSUS', " and"])

m2_al_df['County_Upper'] = m2_al_df['County_Upper'].str.replace(pattern, "", regex=True, flags=re.IGNORECASE)

result_state2 = pd.concat([m2, m2_al_df])

/Users/jasonlim/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

In [89]:
result_state2['total_#_post_id'].sum()

6390905

In [90]:
result_state2.head()

,ET_Firearm_Type,County,State,YEAR,Background_Check,sale_type,sale_buy,total_#_post_id,State_POPULATION,County_join,County_Upper,State_Upper
0,Handguns,Maricopa,Arizona,2018,No,Private Party,For Sale,21523,7158024.0,Maricopa County,MARICOPA COUNTY,ARIZONA
1,Handguns,Hillsborough,Florida,2018,No,Private Party,For Sale,18781,21244317.0,Hillsborough County,HILLSBOROUGH COUNTY,FLORIDA
2,Handguns,Oklahoma,Oklahoma,2018,No,Private Party,For Sale,15865,3940235.0,Oklahoma County,OKLAHOMA COUNTY,OKLAHOMA
3,Handguns,Franklin,Ohio,2018,No,Private Party,For Sale,15487,11676341.0,Franklin County,FRANKLIN COUNTY,OHIO
4,Handguns,Knox,Tennessee,2018,No,Private Party,For Sale,14746,6771631.0,Knox County,KNOX COUNTY,TENNESSEE

In [91]:

result_df2['YEAR'] = result_df2['YEAR'].astype(str)

In [92]:
result_df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9426 entries, 0 to 6379
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   NAME               9426 non-null   object
 1   STNAME             9426 non-null   object
 2   YEAR               9426 non-null   object
 3   COUNTY_POPULATION  9426 non-null   int64
 4   STNAME_Upper       9426 non-null   object
 5   NAME_Upper         9426 non-null   object
dtypes: int64(1), object(5)
memory usage: 515.5+ KB

### 2c. Dummy Rows

Some counties do not have values and some counties only have one or town firearm type. For that, I created dummy rows

In [93]:
# creating columns for each category



# Firearm type 
result_df2['ET_Firearm_Type']="Handguns,Rifles,Assault-style Rifles,Shotguns"


# convert to list
result_df2['ET_Firearm_Type'] = result_df2['ET_Firearm_Type'].str.split(',')


# convert list of pd.Series then stack it
result_df2 = (result_df2
 .set_index(['NAME','STNAME','YEAR','COUNTY_POPULATION','STNAME_Upper','NAME_Upper'])['ET_Firearm_Type']
 .apply(pd.Series)
 .stack()
 .reset_index()
 .rename(columns={0:'ET_Firearm_Type'}))

In [94]:
result_df2.head

<bound method NDFrame.head of                             NAME   STNAME  YEAR  COUNTY_POPULATION  \
0                 Autauga County  Alabama  2018              55533
1                 Autauga County  Alabama  2018              55533
2                 Autauga County  Alabama  2018              55533
3                 Autauga County  Alabama  2018              55533
4                 Baldwin County  Alabama  2018             217855
...                          ...      ...   ...                ...
37699   Yakutat City and Borough   Alaska  2020                579
37700  Yukon-Koyukuk Census Area   Alaska  2020               5230
37701  Yukon-Koyukuk Census Area   Alaska  2020               5230
37702  Yukon-Koyukuk Census Area   Alaska  2020               5230
37703  Yukon-Koyukuk Census Area   Alaska  2020               5230

      STNAME_Upper      NAME_Upper  level_6       ET_Firearm_Type
0          ALABAMA  AUTAUGA COUNTY        0              Handguns
1          ALABAMA  AUTAUGA COUNTY        1                Rifles
2          ALABAMA  AUTAUGA COUNTY        2  Assault-style Rifles
3          ALABAMA  AUTAUGA COUNTY        3              Shotguns
4          ALABAMA  BALDWIN COUNTY        0              Handguns
...            ...             ...      ...                   ...
37699       ALASKA         YAKUTAT        3              Shotguns
37700       ALASKA   YUKON-KOYUKUK        0              Handguns
37701       ALASKA   YUKON-KOYUKUK        1                Rifles
37702       ALASKA   YUKON-KOYUKUK        2  Assault-style Rifles
37703       ALASKA   YUKON-KOYUKUK        3              Shotguns

[37704 rows x 8 columns]>

In [95]:
# Sale Type
result_df2['sale_type'] = "Private Party,Premium Vendor"

result_df2['sale_type'] = result_df2['sale_type'].str.split(',')

result_df2 = (result_df2
 .set_index(['NAME','STNAME','YEAR','COUNTY_POPULATION','STNAME_Upper','NAME_Upper','ET_Firearm_Type'])['sale_type']
 .apply(pd.Series)
 .stack()
 .reset_index()
 .rename(columns={0:'sale_type'}))




result_df2['sale_buy'] = "Want to Buy,For Sale,For Trade"



result_df2['sale_buy'] = result_df2['sale_buy'].str.split(',')

result_df2 = (result_df2
 .set_index(['NAME','STNAME','YEAR','COUNTY_POPULATION','STNAME_Upper','NAME_Upper','ET_Firearm_Type','sale_type'])['sale_buy']
 .apply(pd.Series)
 .stack()
 .reset_index()
 .rename(columns={0:'sale_buy'}))

In [96]:
result_df2.head()

,NAME,STNAME,YEAR,COUNTY_POPULATION,STNAME_Upper,NAME_Upper,ET_Firearm_Type,sale_type,level_8,sale_buy
0,Autauga County,Alabama,2018,55533,ALABAMA,AUTAUGA COUNTY,Handguns,Private Party,0,Want to Buy
1,Autauga County,Alabama,2018,55533,ALABAMA,AUTAUGA COUNTY,Handguns,Private Party,1,For Sale
2,Autauga County,Alabama,2018,55533,ALABAMA,AUTAUGA COUNTY,Handguns,Private Party,2,For Trade
3,Autauga County,Alabama,2018,55533,ALABAMA,AUTAUGA COUNTY,Handguns,Premium Vendor,0,Want to Buy
4,Autauga County,Alabama,2018,55533,ALABAMA,AUTAUGA COUNTY,Handguns,Premium Vendor,1,For Sale

In [97]:
result_df2=result_df2.drop('level_8', axis=1)

In [98]:
result_state2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 43132 entries, 0 to 42865
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ET_Firearm_Type   43132 non-null  object
 1   County            43132 non-null  object
 2   State             43111 non-null  object
 3   YEAR              43132 non-null  object
 4   Background_Check  43111 non-null  object
 5   sale_type         43132 non-null  object
 6   sale_buy          43124 non-null  object
 7   total_#_post_id   43132 non-null  int64
 8   State_POPULATION  43111 non-null  float64
 9   County_join       43132 non-null  object
 10  County_Upper      43132 non-null  object
 11  State_Upper       43132 non-null  object
dtypes: float64(1), int64(1), object(10)
memory usage: 4.3+ MB

In [99]:
new_df = result_df2.merge(result_state2,how='outer', 
                             left_on=['STNAME_Upper', 'NAME_Upper', 'YEAR','ET_Firearm_Type', 'sale_type', 'sale_buy'], 
                             right_on=['State_Upper', 'County_Upper', 'YEAR','ET_Firearm_Type', 'sale_type', 'sale_buy'])

In [100]:
new_df.head()

,NAME,STNAME,YEAR,COUNTY_POPULATION,STNAME_Upper,NAME_Upper,ET_Firearm_Type,sale_type,sale_buy,County,State,Background_Check,total_#_post_id,State_POPULATION,County_join,County_Upper,State_Upper
0,Autauga County,Alabama,2018,55533.0,ALABAMA,AUTAUGA COUNTY,Handguns,Private Party,Want to Buy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Autauga County,Alabama,2018,55533.0,ALABAMA,AUTAUGA COUNTY,Handguns,Private Party,For Sale,Autauga,Alabama,No,7.0,4887681.0,Autauga County,AUTAUGA COUNTY,ALABAMA
2,Autauga County,Alabama,2018,55533.0,ALABAMA,AUTAUGA COUNTY,Handguns,Private Party,For Trade,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Autauga County,Alabama,2018,55533.0,ALABAMA,AUTAUGA COUNTY,Handguns,Premium Vendor,Want to Buy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Autauga County,Alabama,2018,55533.0,ALABAMA,AUTAUGA COUNTY,Handguns,Premium Vendor,For Sale,Autauga,Alabama,Yes,50.0,4887681.0,Autauga County,AUTAUGA COUNTY,ALABAMA

In [101]:
m['total_#_post_id'].sum()

6390905

In [102]:
new_df['total_#_post_id'].sum()

6390905.0

In [103]:
len(new_df)

229317

In [104]:
len(new_df[new_df['NAME'].isnull()])

2636

In [105]:
len(c_pop)*3*4*2*3+2594

228818

In [106]:
new_df.columns

Index(['NAME', 'STNAME', 'YEAR', 'COUNTY_POPULATION', 'STNAME_Upper',
       'NAME_Upper', 'ET_Firearm_Type', 'sale_type', 'sale_buy', 'County',
       'State', 'Background_Check', 'total_#_post_id', 'State_POPULATION',
       'County_join', 'County_Upper', 'State_Upper'],
      dtype='object')

In [107]:
# erase unused and duplicate columns

new_df_final_state = new_df[['NAME', 'STNAME', 'YEAR', 'COUNTY_POPULATION','ET_Firearm_Type', 'County', 'State', 
       'Background_Check', 'sale_type', 'sale_buy', 'total_#_post_id', 'State_POPULATION']]

In [108]:
new_df_final_state.columns

Index(['NAME', 'STNAME', 'YEAR', 'COUNTY_POPULATION', 'ET_Firearm_Type',
       'County', 'State', 'Background_Check', 'sale_type', 'sale_buy',
       'total_#_post_id', 'State_POPULATION'],
      dtype='object')

In [109]:
len(new_df_final_state)

229317

In [110]:
# Created general rule for background check rule


no_bg = ['Alabama','Alaska','Arizona','Arkansas','Florida','Georgia','Idaho','Indiana','Kansas','Kentucky',
         'Louisiana','Maine','Minnesota','Mississippi','Missouri','Montana','New Hampshire','North Dakota',
         'Ohio','Oklahoma','South Carolina','South Dakota','Tennessee','Texas','Utah','West Virginia',
         'Wisconsin', 'Wyoming']
yes_bg = ['California', 'Colorado','Connecticut','Delaware','District of Columbia','Hawaii','Illinois',
          'Massachusetts','New Jersey','New York','Oregon','Rhode Island',
          'Vermont','Washington', 'Nevada','New Mexico','Virginia',]
special_state = ['Pennsylvania','Maryland', 'Iowa','Michigan','Nebraska','North Carolina']

# change to datetime
final_df['listed_date'] = pd.to_datetime(final_df['listed_date'])

#Create a column called category_grouping for 3 groups, Firearm, Firearm_Other, Non-Firearm.

def state_bgc_law_check(df):
    if df['State'] in no_bg :
        return "No background check required"
        # if state is required background check, then it is illegal
    elif df['State'] in yes_bg:
            return "Background check required"
    elif df['State'] in special_state:
           
            return 'Background check required (Handguns Only)'
    else:
        if df['STNAME'] in no_bg :
            return "No background check required"
        elif df['STNAME'] in yes_bg:
            return "Background check required"
        elif df['STNAME'] in special_state:
           
            return 'Background check required (Handguns Only)'

In [111]:
new_df_final_state['state_bgc_law_check'] = new_df_final_state.apply(state_bgc_law_check, axis=1)

/Users/jasonlim/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [112]:
new_df_final_state[new_df_final_state['State']=='Nebraska']['state_bgc_law_check'].value_counts()

Background check required (Handguns Only)    567
Name: state_bgc_law_check, dtype: int64

In [113]:
new_df_final_state['state_bgc_law_check'].value_counts()

No background check required                 150064
Background check required                     45384
Background check required (Handguns Only)     33848
Name: state_bgc_law_check, dtype: int64

In [114]:
# replace nan from STate and county

In [115]:
new_df_final_state['state_bgc_law_check'].isnull().sum()

21

In [116]:
new_df_final_state[new_df_final_state['state_bgc_law_check'].isnull()]

,NAME,STNAME,YEAR,COUNTY_POPULATION,ET_Firearm_Type,County,State,Background_Check,sale_type,sale_buy,total_#_post_id,State_POPULATION,state_bgc_law_check
227346,NaN,NaN,2018,NaN,Rifles,Guilford,NaN,NaN,Private Party,NaN,2.0,NaN,None
227383,NaN,NaN,2018,NaN,Assault-style Rifles,Guilford,NaN,NaN,Private Party,1,1.0,NaN,None
228214,NaN,NaN,2019,NaN,Handguns,Undetermined,NaN,NaN,Private Party,NaN,2.0,NaN,None
228252,NaN,NaN,2019,NaN,Assault-style Rifles,Cumberland,NaN,NaN,Private Party,NaN,1.0,NaN,None
228299,NaN,NaN,2019,NaN,Handguns,Undetermined,NaN,NaN,Private Party,1,1.0,NaN,None
229091,NaN,NaN,2020,NaN,Assault-style Rifles,Undetermined,NaN,NaN,Private Party,1,3.0,NaN,None
229129,NaN,NaN,2020,NaN,Assault-style Rifles,Nye,NaN,NaN,Private Party,1,2.0,NaN,None
229175,NaN,NaN,2020,NaN,Assault-style Rifles,Bonneville,NaN,NaN,Private Party,1,1.0,NaN,None
229177,NaN,NaN,2020,NaN,Assault-style Rifles,Erie,NaN,NaN,Private Party,1,1.0,NaN,None
229178,NaN,NaN,2020,NaN,Assault-style Rifles,Flathead,NaN,NaN,Private Party,1,1.0,NaN,None
229179,NaN,NaN,2020,NaN,Assault-style Rifles,Forrest,NaN,NaN,Private Party,1,1.0,NaN,None
229180,NaN,NaN,2020,NaN,Assault-style Rifles,Hardin,NaN,NaN,Private Party,1,1.0,NaN,None
229181,NaN,NaN,2020,NaN,Assault-style Rifles,Hartford,NaN,NaN,Private Party,1,1.0,NaN,None
229184,NaN,NaN,2020,NaN,Assault-style Rifles,McKinley,NaN,NaN,Private Party,1,1.0,NaN,None
229188,NaN,NaN,2020,NaN,Assault-style Rifles,Salt Lake,NaN,NaN,Private Party,1,1.0,NaN,None
229201,NaN,NaN,2020,NaN,Assault-style Rifles,Washoe,NaN,NaN,Private Party,1,1.0,NaN,None
229236,NaN,NaN,2020,NaN,Rifles,Erie,NaN,NaN,Private Party,NaN,1.0,NaN,None
229242,NaN,NaN,2020,NaN,Rifles,McKinley,NaN,NaN,Private Party,NaN,1.0,NaN,None
229247,NaN,NaN,2020,NaN,Rifles,Salt Lake,NaN,NaN,Private Party,NaN,1.0,NaN,None
229260,NaN,NaN,2020,NaN,Rifles,Washoe,NaN,NaN,Private Party,NaN,1.0,NaN,None
229291,NaN,NaN,2020,NaN,Shotguns,Union,NaN,NaN,Private Party,NaN,1.0,NaN,None

In [117]:
new_df_final_state['STNAME'].isnull().sum()

2636

In [118]:
new_df_final_state['State'].isnull().sum()

186206

In [119]:
len(new_df_final_state[(new_df_final_state['STNAME'].isnull())&(new_df_final_state['State'].isnull())])

21

In [120]:
new_df_final_state['NAME'].isnull().sum()

2636

In [121]:
new_df_final_state['County'].isnull().sum()

186185

In [122]:
new_df_final_state['STNAME'].isnull()

0         False
1         False
2         False
3         False
4         False
          ...
229312     True
229313     True
229314     True
229315     True
229316     True
Name: STNAME, Length: 229317, dtype: bool

In [123]:
new_df_final_state.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 229317 entries, 0 to 229316
Data columns (total 13 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   NAME                 226681 non-null  object
 1   STNAME               226681 non-null  object
 2   YEAR                 229317 non-null  object
 3   COUNTY_POPULATION    226681 non-null  float64
 4   ET_Firearm_Type      229317 non-null  object
 5   County               43132 non-null   object
 6   State                43111 non-null   object
 7   Background_Check     43111 non-null   object
 8   sale_type            229317 non-null  object
 9   sale_buy             229309 non-null  object
 10  total_#_post_id      43132 non-null   float64
 11  State_POPULATION     43111 non-null   float64
 12  state_bgc_law_check  229296 non-null  object
dtypes: float64(3), object(10)
memory usage: 24.5+ MB

In [124]:
new_df_final_state['State'] = new_df_final_state['STNAME'].fillna(new_df_final_state['State'])
new_df_final_state['County'] = new_df_final_state['NAME'].fillna(new_df_final_state['County'])

/Users/jasonlim/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/Users/jasonlim/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

## More Engineering for better visualization
1. adding Unites States for total counts. This needs for trend graph to show all counts
2. For NV, NM, VA adding 0 for visualization

In [125]:
new_df_final_state.head()

,NAME,STNAME,YEAR,COUNTY_POPULATION,ET_Firearm_Type,County,State,Background_Check,sale_type,sale_buy,total_#_post_id,State_POPULATION,state_bgc_law_check
0,Autauga County,Alabama,2018,55533.0,Handguns,Autauga County,Alabama,NaN,Private Party,Want to Buy,NaN,NaN,No background check required
1,Autauga County,Alabama,2018,55533.0,Handguns,Autauga County,Alabama,No,Private Party,For Sale,7.0,4887681.0,No background check required
2,Autauga County,Alabama,2018,55533.0,Handguns,Autauga County,Alabama,NaN,Private Party,For Trade,NaN,NaN,No background check required
3,Autauga County,Alabama,2018,55533.0,Handguns,Autauga County,Alabama,NaN,Premium Vendor,Want to Buy,NaN,NaN,No background check required
4,Autauga County,Alabama,2018,55533.0,Handguns,Autauga County,Alabama,Yes,Premium Vendor,For Sale,50.0,4887681.0,No background check required

In [126]:
new_df_final_state.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 229317 entries, 0 to 229316
Data columns (total 13 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   NAME                 226681 non-null  object
 1   STNAME               226681 non-null  object
 2   YEAR                 229317 non-null  object
 3   COUNTY_POPULATION    226681 non-null  float64
 4   ET_Firearm_Type      229317 non-null  object
 5   County               229317 non-null  object
 6   State                229296 non-null  object
 7   Background_Check     43111 non-null   object
 8   sale_type            229317 non-null  object
 9   sale_buy             229309 non-null  object
 10  total_#_post_id      43132 non-null   float64
 11  State_POPULATION     43111 non-null   float64
 12  state_bgc_law_check  229296 non-null  object
dtypes: float64(3), object(10)
memory usage: 24.5+ MB

In [127]:
#new_df_final_state[new_df_final_state['State']=='Nevada'].to_csv("Nevada.csv")

In [128]:
new_df_final_state[new_df_final_state['State']=='New Mexico']

,NAME,STNAME,YEAR,COUNTY_POPULATION,ET_Firearm_Type,County,State,Background_Check,sale_type,sale_buy,total_#_post_id,State_POPULATION,state_bgc_law_check
42390,Bernalillo County,New Mexico,2018,678034.0,Handguns,Bernalillo County,New Mexico,No,Private Party,Want to Buy,126.0,2092741.0,Background check required
42391,Bernalillo County,New Mexico,2018,678034.0,Handguns,Bernalillo County,New Mexico,No,Private Party,For Sale,3641.0,2092741.0,Background check required
42392,Bernalillo County,New Mexico,2018,678034.0,Handguns,Bernalillo County,New Mexico,No,Private Party,For Trade,287.0,2092741.0,Background check required
42393,Bernalillo County,New Mexico,2018,678034.0,Handguns,Bernalillo County,New Mexico,NaN,Premium Vendor,Want to Buy,NaN,NaN,Background check required
42394,Bernalillo County,New Mexico,2018,678034.0,Handguns,Bernalillo County,New Mexico,Yes,Premium Vendor,For Sale,416.0,2092741.0,Background check required
...,...,...,...,...,...,...,...,...,...,...,...,...,...
229195,NaN,NaN,2020,NaN,Assault-style Rifles,Undetermined,New Mexico,Yes,Private Party,For Trade,1.0,2096829.0,Background check required
229223,NaN,NaN,2020,NaN,Handguns,Undetermined,New Mexico,Yes,Private Party,For Trade,1.0,2096829.0,Background check required
229255,NaN,NaN,2020,NaN,Rifles,Undetermined,New Mexico,Yes,Private Party,For Trade,1.0,2096829.0,Background check required
229282,NaN,NaN,2020,NaN,Shotguns,Undetermined,New Mexico,Yes,Premium Vendor,For Sale,1.0,2096829.0,Background check required
229283,NaN,NaN,2020,NaN,Shotguns,Undetermined,New Mexico,Yes,Private Party,For Trade,1.0,2096829.0,Background check required

In [129]:
new_df_final_state['sale_buy'].unique()

array(['Want to Buy', 'For Sale', 'For Trade', nan, '1'], dtype=object)

In [154]:
# create dummy rows for NV 2020 and NM 2020 because VA started new background check law on 7/1/2020
# Nevada
NV_2020_df = pd.DataFrame({"YEAR": ['2020','2020','2020','2020'],
                           "ET_Firearm_Type":['Handguns', 'Rifles', 'Assault-style Rifles', 'Shotguns'], 
                           "State": ['Nevada','Nevada','Nevada','Nevada'],
                          "total_#_post_id":[0,0,0,0]})

In [155]:
NV_2020_df['Background_Check'] = "Yes,No"
NV_2020_df['Background_Check'] = NV_2020_df['Background_Check'].str.split(',')

NV_2020_df = (NV_2020_df
 .set_index(['YEAR','ET_Firearm_Type','State', 'total_#_post_id'])['Background_Check']
 .apply(pd.Series)
 .stack()
 .reset_index()
 .rename(columns={0:'Background_Check'}))

NV_2020_df['sale_type'] = "Private Party,Premium Vendor"

NV_2020_df['sale_type'] = NV_2020_df['sale_type'].str.split(',')

NV_2020_df = (NV_2020_df
 .set_index(['YEAR','ET_Firearm_Type','Background_Check','State', 'total_#_post_id'])['sale_type']
 .apply(pd.Series)
 .stack()
 .reset_index()
 .rename(columns={0:'sale_type'}))




NV_2020_df['sale_buy'] = "Want to Buy,For Sale,For Trade"



NV_2020_df['sale_buy'] = NV_2020_df['sale_buy'].str.split(',')

NV_2020_df = (NV_2020_df
 .set_index(['YEAR','ET_Firearm_Type','Background_Check','sale_type','State', 'total_#_post_id'])['sale_buy']
 .apply(pd.Series)
 .stack()
 .reset_index()
 .rename(columns={0:'sale_buy'}))
NV_2020_df = NV_2020_df.drop('level_6', axis=1)
NV_2020_df['state_bgc_law_check'] = 'Background check required'

In [156]:
NV_2020_df.head()

,YEAR,ET_Firearm_Type,Background_Check,sale_type,State,total_#_post_id,sale_buy,state_bgc_law_check
0,2020,Handguns,Yes,Private Party,Nevada,0,Want to Buy,Background check required
1,2020,Handguns,Yes,Private Party,Nevada,0,For Sale,Background check required
2,2020,Handguns,Yes,Private Party,Nevada,0,For Trade,Background check required
3,2020,Handguns,Yes,Premium Vendor,Nevada,0,Want to Buy,Background check required
4,2020,Handguns,Yes,Premium Vendor,Nevada,0,For Sale,Background check required

In [157]:
NV_2020_df.tail()

,YEAR,ET_Firearm_Type,Background_Check,sale_type,State,total_#_post_id,sale_buy,state_bgc_law_check
43,2020,Shotguns,No,Private Party,Nevada,0,For Sale,Background check required
44,2020,Shotguns,No,Private Party,Nevada,0,For Trade,Background check required
45,2020,Shotguns,No,Premium Vendor,Nevada,0,Want to Buy,Background check required
46,2020,Shotguns,No,Premium Vendor,Nevada,0,For Sale,Background check required
47,2020,Shotguns,No,Premium Vendor,Nevada,0,For Trade,Background check required

In [158]:
# New Mexico
NM_2020_df= pd.DataFrame({"YEAR": ['2020','2020','2020','2020'],
                           "ET_Firearm_Type":['Handguns', 'Rifles', 'Assault-style Rifles', 'Shotguns'], 
                           "State": ['New Mexico','New Mexico','New Mexico','New Mexico'],
                          "total_#_post_id":[0,0,0,0]})

NM_2020_df['Background_Check'] = "Yes,No"
NM_2020_df['Background_Check'] = NM_2020_df['Background_Check'].str.split(',')

NM_2020_df = (NM_2020_df
 .set_index(['YEAR','ET_Firearm_Type','State', 'total_#_post_id'])['Background_Check']
 .apply(pd.Series)
 .stack()
 .reset_index()
 .rename(columns={0:'Background_Check'}))

NM_2020_df['sale_type'] = "Private Party,Premium Vendor"

NM_2020_df['sale_type'] = NM_2020_df['sale_type'].str.split(',')

NM_2020_df = (NM_2020_df
 .set_index(['YEAR','ET_Firearm_Type','Background_Check','State', 'total_#_post_id'])['sale_type']
 .apply(pd.Series)
 .stack()
 .reset_index()
 .rename(columns={0:'sale_type'}))




NM_2020_df['sale_buy'] = "Want to Buy,For Sale,For Trade"



NM_2020_df['sale_buy'] = NM_2020_df['sale_buy'].str.split(',')

NM_2020_df = (NM_2020_df
 .set_index(['YEAR','ET_Firearm_Type','Background_Check','sale_type','State', 'total_#_post_id'])['sale_buy']
 .apply(pd.Series)
 .stack()
 .reset_index()
 .rename(columns={0:'sale_buy'}))
NM_2020_df = NM_2020_df.drop('level_6', axis=1)
NM_2020_df['state_bgc_law_check'] = 'Background check required'

In [159]:
NM_2020_df.head()

,YEAR,ET_Firearm_Type,Background_Check,sale_type,State,total_#_post_id,sale_buy,state_bgc_law_check
0,2020,Handguns,Yes,Private Party,New Mexico,0,Want to Buy,Background check required
1,2020,Handguns,Yes,Private Party,New Mexico,0,For Sale,Background check required
2,2020,Handguns,Yes,Private Party,New Mexico,0,For Trade,Background check required
3,2020,Handguns,Yes,Premium Vendor,New Mexico,0,Want to Buy,Background check required
4,2020,Handguns,Yes,Premium Vendor,New Mexico,0,For Sale,Background check required

In [160]:
# append
new_df_final_state = new_df_final_state.append([NV_2020_df,NM_2020_df], ignore_index=True)

In [161]:
len(new_df_final_state)

229413

In [162]:
# getting united states

us = new_df_final_state.groupby(["YEAR", 'ET_Firearm_Type', 'Background_Check','sale_type', 'sale_buy'])\
['total_#_post_id'].sum().reset_index()

In [163]:
us['State'] = "* United States"
us['state_bgc_law_check'] = 'United States'

In [164]:
pop['STNAME'].unique()

array(['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California',
       'Colorado', 'Connecticut', 'Delaware', 'District of Columbia',
       'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana',
       'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland',
       'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi',
       'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire',
       'New Jersey', 'New Mexico', 'New York', 'North Carolina',
       'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania',
       'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee',
       'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington',
       'West Virginia', 'Wisconsin', 'Wyoming'], dtype=object)

In [165]:
us.head()

,YEAR,ET_Firearm_Type,Background_Check,sale_type,sale_buy,total_#_post_id,State,state_bgc_law_check
0,2018,Assault-style Rifles,No,Private Party,For Sale,146545.0,* United States,United States
1,2018,Assault-style Rifles,No,Private Party,For Trade,7420.0,* United States,United States
2,2018,Assault-style Rifles,No,Private Party,Want to Buy,3782.0,* United States,United States
3,2018,Assault-style Rifles,Yes,Premium Vendor,For Sale,26859.0,* United States,United States
4,2018,Assault-style Rifles,Yes,Premium Vendor,For Trade,1.0,* United States,United States

In [166]:
new_df_final_state = new_df_final_state.append(us, ignore_index=True)

In [167]:
len(new_df_final_state)

229530

In [168]:
# eliminate null and 1

new_df_final_state = new_df_final_state[new_df_final_state['sale_buy']!='1']

new_df_final_state = new_df_final_state[new_df_final_state['sale_buy'].notnull()]

In [169]:
len(new_df_final_state)

229509

In [170]:
new_df_final_state.to_csv('agg_result_final.csv', index=False)

# Narrative

In [171]:
final_df.head()

,uid,store_id,post_id,listed_date,title,category,firearm_type,County,location,action,manufacturer,caliber,registered_date,price_num,sale_type,post_content,City,State,State_id,city_lat,city_lng,state_lat,state_lng,final_lat,final_lng,extract_date,post_url,firearm_accessories,sale_buy,uid_Change,store_id_Change,category_Change,firearm_type_Change,action_Change,manufacturer_Change,caliber_Change,registered_date_Change,sale_type_Change,listed_date_Change,location_Change,price_num_Change,post_content_Change,title_Change,Model_Title_Cnt,Model_Content_Cnt,Feature_Title_Cnt,Feature_Content_Cnt,Exclude_Title_Cnt,Exclude_Content_Cnt,Model_Title,Model_Content,Feature_Title,Feature_Content,Exclude_Title,Exclude_Content,action_exclusion,Model_Title_hit,Model_Content_hit,Feature_Title_hit,Feature_Content_hit,Exclude_Title_hit,Exclude_Content_hit,UniquePostIdFlag,RecordCount,DupeRemoveFlag,uid_ChangeCount,store_id_ChangeCount,listed_date_ChangeCount,title_ChangeCount,category_ChangeCount,firearm_type_ChangeCount,location_ChangeCount,action_ChangeCount,manufacturer_ChangeCount,caliber_ChangeCount,registered_date_ChangeCount,price_num_ChangeCount,sale_type_ChangeCount,post_content_ChangeCount,data_filter,dup_filter_group,post_process,Category_Group,ET_Firearm_Type,Background_Check
0,116028.0,NaN,7769732,2018-01-07,For Sale: Small Collection of German Handguns.,Handguns,Pistol,Greene,"SPFD, Springfield, Missouri",NaN,NaN,NaN,NaN,1.0,Private Party,Small Collection of German Handguns. 7 Lugers ...,Springfield,Missouri,MO,37.258072,-93.343674,38.310318,-92.421555,37.258072,-93.343674,2018-01-07 16:03:34.680000000,http://www.armslist.com/posts/7769732,Firearms,For Sale,False,False,False,False,False,False,False,False,False,True,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.000000e+04,K2,0.0,Firearm Post,Handguns,No
1,115037.0,NaN,7767216,2018-01-07,For Sale/Trade: 300AAC AR15 Pistol Upper,Handguns,Pistol,Madison,"Huntsville, Huntsville, Alabama",Single Action,Anderson Manufacturing,NaN,2014-02-09,400.0,Private Party,"300AAC AR15 Pistol Upper:ALG 10"" RailNoveske K...",Huntsville,Alabama,AL,34.733963,-86.522911,32.609589,-86.729843,34.733963,-86.522911,2018-01-07 16:03:35.987000000,http://www.armslist.com/posts/7767216,Firearms,For Sale,True,True,True,True,True,True,True,True,True,True,True,True,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.111111e+13,NaN,0.0,Firearm Post,Handguns,No
2,115037.0,NaN,7767236,2018-01-07,For Sale: S&W Model 36-10 Revolver,Handguns,Revolver,Madison,"Huntsville, Huntsville, Alabama",Double / Single Action,Smith & Wesson,38 S&W Special,2014-02-09,550.0,Private Party,S&W Model 36-10 RevolverPurchased new Summer 2...,Huntsville,Alabama,AL,34.733963,-86.522911,32.609589,-86.729843,34.733963,-86.522911,2018-01-07 16:03:36.943000000,http://www.armslist.com/posts/7767236,Firearms,For Sale,False,False,False,False,False,False,False,False,False,True,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000e+04,K2,0.0,Firearm Post,Handguns,No
3,99474.0,NaN,7772635,2018-01-07,For Sale: Glock 19 Gen 4 with front serrations,Handguns,Pistol,Hillsborough,"Dover, Tampa/St. Pete, Florida",Striker Fire,Glock,9mm Luger (9x19),2017-07-25,550.0,Private Party,LNIB. Has front serrations from factory. Pol...,Dover,Florida,FL,27.975742,-82.240417,27.771553,-83.772789,27.975742,-82.240417,2018-01-07 16:03:37.730000000,http://www.armslist.com/posts/7772635,Firearms,For Sale,True,True,True,True,True,True,True,True,True,True,True,True,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.111111e+13,NaN,0.0,Firearm Post,Handguns,No
4,3319.0,NaN,6640627,2018-01-07,For Sale: SW 625JM,Handguns,Revolver,San Francisco,"Martinez, San Francisco, California",Double / Single Action,Smith & Wesson,45 ACP,2015-07-08,800.0,Private Party,I have a smith and wesson model 625 JM for sal...,San Francisco,California,CA,37.784828,-122.727800,37.286072,-119.279170,37.784828,-122.727800,2018-01-07 16:03:38.520000000,http://www.armslist.com/posts/6640627,Firearms,For Sale,False,False,False,False,False,False,False,False,False,True,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000e+04,K2,0.0,Firearm Post,Handguns,Yes

In [172]:
len(final_df)

9054047

In [207]:
len(final_df[(final_df['sale_buy']=='For Sale')&
         (final_df['Category_Group']=='Firearm Post')])

6173844

In [208]:
6173844/9054047

0.6818877790230159

In [173]:
final_df['sale_buy'].value_counts()

For Sale       8432600
For Trade       369515
Want to Buy     251906
1                   16
Name: sale_buy, dtype: int64

### average number of posts for all firearms for all seller types each year.

In [174]:
len(final_df[(final_df['sale_buy']=='For Sale')&(final_df['DupeRemoveFlag']!=1)])/3

2694169.6666666665

### yearly average for the number of posts for firearms for sale by unlicensed sellers in all states.

In [175]:
final_df2.head()

,uid,store_id,post_id,listed_date,title,category,firearm_type,County,location,action,manufacturer,caliber,registered_date,price_num,sale_type,post_content,City,State,State_id,city_lat,city_lng,state_lat,state_lng,final_lat,final_lng,extract_date,post_url,firearm_accessories,sale_buy,uid_Change,store_id_Change,category_Change,firearm_type_Change,action_Change,manufacturer_Change,caliber_Change,registered_date_Change,sale_type_Change,listed_date_Change,location_Change,price_num_Change,post_content_Change,title_Change,Model_Title_Cnt,Model_Content_Cnt,Feature_Title_Cnt,Feature_Content_Cnt,Exclude_Title_Cnt,Exclude_Content_Cnt,Model_Title,Model_Content,Feature_Title,Feature_Content,Exclude_Title,Exclude_Content,action_exclusion,Model_Title_hit,Model_Content_hit,Feature_Title_hit,Feature_Content_hit,Exclude_Title_hit,Exclude_Content_hit,UniquePostIdFlag,RecordCount,DupeRemoveFlag,uid_ChangeCount,store_id_ChangeCount,listed_date_ChangeCount,title_ChangeCount,category_ChangeCount,firearm_type_ChangeCount,location_ChangeCount,action_ChangeCount,manufacturer_ChangeCount,caliber_ChangeCount,registered_date_ChangeCount,price_num_ChangeCount,sale_type_ChangeCount,post_content_ChangeCount,data_filter,dup_filter_group,post_process,Category_Group,ET_Firearm_Type,Background_Check
0,116028.0,NaN,7769732,2018-01-07,For Sale: Small Collection of German Handguns.,Handguns,Pistol,Greene,"SPFD, Springfield, Missouri",NaN,NaN,NaN,NaN,1.0,Private Party,Small Collection of German Handguns. 7 Lugers ...,Springfield,Missouri,MO,37.258072,-93.343674,38.310318,-92.421555,37.258072,-93.343674,2018-01-07 16:03:34.680000000,http://www.armslist.com/posts/7769732,Firearms,For Sale,False,False,False,False,False,False,False,False,False,True,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.000000e+04,K2,0.0,Firearm Post,Handguns,No
1,115037.0,NaN,7767216,2018-01-07,For Sale/Trade: 300AAC AR15 Pistol Upper,Handguns,Pistol,Madison,"Huntsville, Huntsville, Alabama",Single Action,Anderson Manufacturing,NaN,2014-02-09,400.0,Private Party,"300AAC AR15 Pistol Upper:ALG 10"" RailNoveske K...",Huntsville,Alabama,AL,34.733963,-86.522911,32.609589,-86.729843,34.733963,-86.522911,2018-01-07 16:03:35.987000000,http://www.armslist.com/posts/7767216,Firearms,For Sale,True,True,True,True,True,True,True,True,True,True,True,True,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.111111e+13,NaN,0.0,Firearm Post,Handguns,No
2,115037.0,NaN,7767236,2018-01-07,For Sale: S&W Model 36-10 Revolver,Handguns,Revolver,Madison,"Huntsville, Huntsville, Alabama",Double / Single Action,Smith & Wesson,38 S&W Special,2014-02-09,550.0,Private Party,S&W Model 36-10 RevolverPurchased new Summer 2...,Huntsville,Alabama,AL,34.733963,-86.522911,32.609589,-86.729843,34.733963,-86.522911,2018-01-07 16:03:36.943000000,http://www.armslist.com/posts/7767236,Firearms,For Sale,False,False,False,False,False,False,False,False,False,True,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000e+04,K2,0.0,Firearm Post,Handguns,No
3,99474.0,NaN,7772635,2018-01-07,For Sale: Glock 19 Gen 4 with front serrations,Handguns,Pistol,Hillsborough,"Dover, Tampa/St. Pete, Florida",Striker Fire,Glock,9mm Luger (9x19),2017-07-25,550.0,Private Party,LNIB. Has front serrations from factory. Pol...,Dover,Florida,FL,27.975742,-82.240417,27.771553,-83.772789,27.975742,-82.240417,2018-01-07 16:03:37.730000000,http://www.armslist.com/posts/7772635,Firearms,For Sale,True,True,True,True,True,True,True,True,True,True,True,True,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.111111e+13,NaN,0.0,Firearm Post,Handguns,No
4,3319.0,NaN,6640627,2018-01-07,For Sale: SW 625JM,Handguns,Revolver,San Francisco,"Martinez, San Francisco, California",Double / Single Action,Smith & Wesson,45 ACP,2015-07-08,800.0,Private Party,I have a smith and wesson model 625 JM for sal...,San Francisco,California,CA,37.784828,-122.727800,37.286072,-119.279170,37.784828,-122.727800,2018-01-07 16:03:38.520000000,http://www.armslist.com/posts/6640627,Firearms,For Sale,False,False,False,False,False,False,False,False,False,True,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000e+04,K2,0.0,Firearm Post,Handguns,Yes

# Removing Duperemoveflag ==1 and not firearm 

#final_df2 = final_df[(final_df['DupeRemoveFlag']!=1) &
#                    (final_df['ET_Firearm_Type']!="Not_Firearm") &
#                    (final_df['State'] != 'Puerto Rico')&
#                    (final_df['State'] != 'Guam')]

##### of ads from unlicensed sellers in all states. yearly average. no US territories. deduplicated. - firearm only

In [210]:
len(final_df2[(final_df2['sale_buy']=='For Sale')&
            (final_df2['sale_type']=='Private Party')])

4728096

In [211]:
4728096/3

1576032.0

In [209]:
len(final_df2[final_df2['sale_buy']=='For Sale'])

5906395

In [212]:
4728096/5906395

0.8005045378780119

##### of ads from licensed dealers/premium vendors in all states. yearly average. no US territories. deduplicated. firearm only

In [213]:
len(final_df2[(final_df2['sale_buy']=='For Sale')&
            (final_df2['sale_type']=='Premium Vendor')])

1178299

In [177]:
len(final_df2[(final_df2['sale_buy']=='For Sale')&
            (final_df2['sale_type']=='Premium Vendor')])/3

392766.3333333333

#### # of ads from unlicensed sellers in states that do not require background checks. yearly average. no US territories. deduplicated.

#### I already applied background law changes for NV, NM, VA. Also, handgun only for special states. Please see

def legal_check(df):
    # First check it is Firearm post or not
    if (df['Category_Group'] == "Firearm Post") & (df['sale_type'] =='Private Party') :
        # if state is no background check, then it is legal
        if df['State'] in no_bg :
            return "No"
        # if state is required background check, then it is illegal
        elif df['State'] in yes_bg:
            return "Yes"
        elif df['State'] in special_state:
            nv_date  = pd.to_datetime('01-01-2020').date()
            nm_date = pd.to_datetime('07-01-2019').date()
            vi_date = pd.to_datetime('07-01-2020').date()
            if (df['State']=='Nevada') & (df['listed_date']< nv_date):
                return 'No'
            elif (df['State']=='New Mexico') & (df['listed_date']< nm_date):
                return 'No'
            elif (df['State']=='Virginia') & (df['listed_date']< vi_date):
                return 'No'
            elif (df['State']=='Maryland') & (df['ET_Firearm_Type']!='Handguns'):
                return 'No'
            elif (df['State']=='Pennsylvania') & (df['ET_Firearm_Type']!='Handguns'):
                return 'No'
            elif (df['State']=='Iowa') & (df['ET_Firearm_Type']!='Handguns'):
                return 'No'
            elif (df['State']=='Michigan') & (df['ET_Firearm_Type']!='Handguns'):
                return 'No'
            elif (df['State']=='Nebraska') & (df['ET_Firearm_Type']!='Handguns'):
                return 'No'
            elif (df['State']=='North Carolina') & (df['ET_Firearm_Type']!='Handguns'):
                return 'No'
            else:
                return 'Yes'
    elif (df['Category_Group'] == "Firearm Post") & (df['sale_type'] =='Premium Vendor') :
        return 'Yes'
    else:
        return "Not_Firearm_Post"

In [215]:
len(final_df2[(final_df2['sale_buy']=='For Sale')&
            (final_df2['Background_Check']=='No')&
             (final_df2['sale_type']=='Private Party')])

3676591

In [178]:
len(final_df2[(final_df2['sale_buy']=='For Sale')&
            (final_df2['Background_Check']=='No')])/3

1225530.3333333333

In [179]:
# not accounting new laws

In [180]:
new_df_final_state.head()

,NAME,STNAME,YEAR,COUNTY_POPULATION,ET_Firearm_Type,County,State,Background_Check,sale_type,sale_buy,total_#_post_id,State_POPULATION,state_bgc_law_check
0,Autauga County,Alabama,2018,55533.0,Handguns,Autauga County,Alabama,NaN,Private Party,Want to Buy,NaN,NaN,No background check required
1,Autauga County,Alabama,2018,55533.0,Handguns,Autauga County,Alabama,No,Private Party,For Sale,7.0,4887681.0,No background check required
2,Autauga County,Alabama,2018,55533.0,Handguns,Autauga County,Alabama,NaN,Private Party,For Trade,NaN,NaN,No background check required
3,Autauga County,Alabama,2018,55533.0,Handguns,Autauga County,Alabama,NaN,Premium Vendor,Want to Buy,NaN,NaN,No background check required
4,Autauga County,Alabama,2018,55533.0,Handguns,Autauga County,Alabama,Yes,Premium Vendor,For Sale,50.0,4887681.0,No background check required

In [181]:
new_df_final_state[new_df_final_state['STNAME']=='New Mexico']

,NAME,STNAME,YEAR,COUNTY_POPULATION,ET_Firearm_Type,County,State,Background_Check,sale_type,sale_buy,total_#_post_id,State_POPULATION,state_bgc_law_check
42390,Bernalillo County,New Mexico,2018,678034.0,Handguns,Bernalillo County,New Mexico,No,Private Party,Want to Buy,126.0,2092741.0,Background check required
42391,Bernalillo County,New Mexico,2018,678034.0,Handguns,Bernalillo County,New Mexico,No,Private Party,For Sale,3641.0,2092741.0,Background check required
42392,Bernalillo County,New Mexico,2018,678034.0,Handguns,Bernalillo County,New Mexico,No,Private Party,For Trade,287.0,2092741.0,Background check required
42393,Bernalillo County,New Mexico,2018,678034.0,Handguns,Bernalillo County,New Mexico,NaN,Premium Vendor,Want to Buy,NaN,NaN,Background check required
42394,Bernalillo County,New Mexico,2018,678034.0,Handguns,Bernalillo County,New Mexico,Yes,Premium Vendor,For Sale,416.0,2092741.0,Background check required
...,...,...,...,...,...,...,...,...,...,...,...,...,...
192732,Valencia County,New Mexico,2020,76688.0,Shotguns,Valencia County,New Mexico,NaN,Private Party,For Sale,NaN,NaN,Background check required
192733,Valencia County,New Mexico,2020,76688.0,Shotguns,Valencia County,New Mexico,NaN,Private Party,For Trade,NaN,NaN,Background check required
192734,Valencia County,New Mexico,2020,76688.0,Shotguns,Valencia County,New Mexico,NaN,Premium Vendor,Want to Buy,NaN,NaN,Background check required
192735,Valencia County,New Mexico,2020,76688.0,Shotguns,Valencia County,New Mexico,NaN,Premium Vendor,For Sale,NaN,NaN,Background check required
192736,Valencia County,New Mexico,2020,76688.0,Shotguns,Valencia County,New Mexico,NaN,Premium Vendor,For Trade,NaN,NaN,Background check required

In [182]:
new_df_final_state[(new_df_final_state['state_bgc_law_check']=='No background check required')&
                  (new_df_final_state['sale_buy']=='For Sale')&
                  (new_df_final_state['sale_type']=='Private Party')]['total_#_post_id'].sum()

3143585.0

In [183]:
3143585.0/3

1047861.6666666666

In [184]:
final_df['category'].value_counts()

Handguns                       3683216
Rifles                         2431037
Gun Parts                       609792
Shotguns                        574172
Ammo                            498132
Optics                          304039
Magazines                       175635
Reloading                       129878
Tactical Gear                    90898
Antique Firearms                 89770
Holsters                         89309
Knives                           72265
Miscellaneous                    68940
Muzzle Loaders                   46547
Archery                          44737
NFA Firearms                     27132
Air Guns                         18770
Gun Safes                        18691
Targets and Range Equipment      17708
Vehicles                         16274
Hunting Gear                     14274
Services                         12248
Fishing Gear                      4890
Events                            4238
Paintball/Airsoft                 3604
Farming Equipment                 3112
Firearms Training                 2412
Body Armor                        2311
All Categories                      16
Name: category, dtype: int64

In [185]:
final_df['category'].value_counts()

Handguns                       3683216
Rifles                         2431037
Gun Parts                       609792
Shotguns                        574172
Ammo                            498132
Optics                          304039
Magazines                       175635
Reloading                       129878
Tactical Gear                    90898
Antique Firearms                 89770
Holsters                         89309
Knives                           72265
Miscellaneous                    68940
Muzzle Loaders                   46547
Archery                          44737
NFA Firearms                     27132
Air Guns                         18770
Gun Safes                        18691
Targets and Range Equipment      17708
Vehicles                         16274
Hunting Gear                     14274
Services                         12248
Fishing Gear                      4890
Events                            4238
Paintball/Airsoft                 3604
Farming Equipment                 3112
Firearms Training                 2412
Body Armor                        2311
All Categories                      16
Name: category, dtype: int64

# Vetting 

Below section is for data vetting of dashboard.

In [188]:
final_df2.head()

,uid,store_id,post_id,listed_date,title,category,firearm_type,County,location,action,manufacturer,caliber,registered_date,price_num,sale_type,post_content,City,State,State_id,city_lat,city_lng,state_lat,state_lng,final_lat,final_lng,extract_date,post_url,firearm_accessories,sale_buy,uid_Change,store_id_Change,category_Change,firearm_type_Change,action_Change,manufacturer_Change,caliber_Change,registered_date_Change,sale_type_Change,listed_date_Change,location_Change,price_num_Change,post_content_Change,title_Change,Model_Title_Cnt,Model_Content_Cnt,Feature_Title_Cnt,Feature_Content_Cnt,Exclude_Title_Cnt,Exclude_Content_Cnt,Model_Title,Model_Content,Feature_Title,Feature_Content,Exclude_Title,Exclude_Content,action_exclusion,Model_Title_hit,Model_Content_hit,Feature_Title_hit,Feature_Content_hit,Exclude_Title_hit,Exclude_Content_hit,UniquePostIdFlag,RecordCount,DupeRemoveFlag,uid_ChangeCount,store_id_ChangeCount,listed_date_ChangeCount,title_ChangeCount,category_ChangeCount,firearm_type_ChangeCount,location_ChangeCount,action_ChangeCount,manufacturer_ChangeCount,caliber_ChangeCount,registered_date_ChangeCount,price_num_ChangeCount,sale_type_ChangeCount,post_content_ChangeCount,data_filter,dup_filter_group,post_process,Category_Group,ET_Firearm_Type,Background_Check
0,116028.0,NaN,7769732,2018-01-07,For Sale: Small Collection of German Handguns.,Handguns,Pistol,Greene,"SPFD, Springfield, Missouri",NaN,NaN,NaN,NaN,1.0,Private Party,Small Collection of German Handguns. 7 Lugers ...,Springfield,Missouri,MO,37.258072,-93.343674,38.310318,-92.421555,37.258072,-93.343674,2018-01-07 16:03:34.680000000,http://www.armslist.com/posts/7769732,Firearms,For Sale,False,False,False,False,False,False,False,False,False,True,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.000000e+04,K2,0.0,Firearm Post,Handguns,No
1,115037.0,NaN,7767216,2018-01-07,For Sale/Trade: 300AAC AR15 Pistol Upper,Handguns,Pistol,Madison,"Huntsville, Huntsville, Alabama",Single Action,Anderson Manufacturing,NaN,2014-02-09,400.0,Private Party,"300AAC AR15 Pistol Upper:ALG 10"" RailNoveske K...",Huntsville,Alabama,AL,34.733963,-86.522911,32.609589,-86.729843,34.733963,-86.522911,2018-01-07 16:03:35.987000000,http://www.armslist.com/posts/7767216,Firearms,For Sale,True,True,True,True,True,True,True,True,True,True,True,True,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.111111e+13,NaN,0.0,Firearm Post,Handguns,No
2,115037.0,NaN,7767236,2018-01-07,For Sale: S&W Model 36-10 Revolver,Handguns,Revolver,Madison,"Huntsville, Huntsville, Alabama",Double / Single Action,Smith & Wesson,38 S&W Special,2014-02-09,550.0,Private Party,S&W Model 36-10 RevolverPurchased new Summer 2...,Huntsville,Alabama,AL,34.733963,-86.522911,32.609589,-86.729843,34.733963,-86.522911,2018-01-07 16:03:36.943000000,http://www.armslist.com/posts/7767236,Firearms,For Sale,False,False,False,False,False,False,False,False,False,True,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000e+04,K2,0.0,Firearm Post,Handguns,No
3,99474.0,NaN,7772635,2018-01-07,For Sale: Glock 19 Gen 4 with front serrations,Handguns,Pistol,Hillsborough,"Dover, Tampa/St. Pete, Florida",Striker Fire,Glock,9mm Luger (9x19),2017-07-25,550.0,Private Party,LNIB. Has front serrations from factory. Pol...,Dover,Florida,FL,27.975742,-82.240417,27.771553,-83.772789,27.975742,-82.240417,2018-01-07 16:03:37.730000000,http://www.armslist.com/posts/7772635,Firearms,For Sale,True,True,True,True,True,True,True,True,True,True,True,True,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.111111e+13,NaN,0.0,Firearm Post,Handguns,No
4,3319.0,NaN,6640627,2018-01-07,For Sale: SW 625JM,Handguns,Revolver,San Francisco,"Martinez, San Francisco, California",Double / Single Action,Smith & Wesson,45 ACP,2015-07-08,800.0,Private Party,I have a smith and wesson model 625 JM for sal...,San Francisco,California,CA,37.784828,-122.727800,37.286072,-119.279170,37.784828,-122.727800,2018-01-07 16:03:38.520000000,http://www.armslist.com/posts/6640627,Firearms,For Sale,False,False,False,False,False,False,False,False,False,True,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000e+04,K2,0.0,Firearm Post,Handguns,Yes

## Dashboard 1

In [189]:


# Firearm Type : All, posting Type: For Sale, Seller Type: Unlicensed Seller
len(final_df2[(final_df2['sale_buy']=='For Sale')&
            (final_df2['sale_type']=='Private Party')])

4728096

In [190]:
# dashboard said 1,576,032 posts each year
4728096/3

1576032.0

In [191]:
# Tooltip
# 1,225,530 or 78%
len(final_df2[(final_df2['sale_buy']=='For Sale')&
            (final_df2['sale_type']=='Private Party')&
             (final_df2['Background_Check']=='No')])

3676591

In [192]:
# 1,225,530 or 78%
print(3676591/3)
print(3676591/4728096)

1225530.3333333333
0.7776049809479334

In [193]:
final_df2[(final_df2['sale_buy']=='For Sale')&
            (final_df2['sale_type']=='Private Party')&
             (final_df2['Background_Check']=='No')]['ET_Firearm_Type'].value_counts()

Handguns                1774613
Rifles                  1092657
Assault-style Rifles     461867
Shotguns                 347454
Name: ET_Firearm_Type, dtype: int64

In [194]:
# For Handgun
print(1774613/3)

591537.6666666666

## Dashboard 2

In [195]:

# Arizona
len(final_df2[(final_df2['sale_buy']=='For Sale')&
            (final_df2['sale_type']=='Private Party')&
             (final_df2['Background_Check']=='No')&
             (final_df2['State']=='Arizona')])

266584

In [196]:
266584/3

88861.33333333333

## Dashboard 3

In [197]:
# usa
len(final_df2[(final_df2['sale_buy']=='For Sale')&
            (final_df2['sale_type']=='Private Party')&
             (final_df2['Background_Check']=='No')])

3676591

In [200]:
# 2018 1.16 M, 2019 1,329,519, 2020, 1,190,213
final_df2[(final_df2['sale_buy']=='For Sale')&
            (final_df2['sale_type']=='Private Party')&
             (final_df2['Background_Check']=='No')].groupby(final_df2.listed_date.dt.year)['post_id'].count()

listed_date
2018    1156859
2019    1329519
2020    1190213
Name: post_id, dtype: int64

In [201]:
# NV

final_df2[(final_df2['sale_buy']=='For Sale')&
            (final_df2['sale_type']=='Private Party')&
             (final_df2['Background_Check']=='No')&
         (final_df2['State']=='Nevada')].groupby(final_df2.listed_date.dt.year)['post_id'].count()

listed_date
2018    33266
2019    42492
Name: post_id, dtype: int64

## Dashboard 4

In [202]:
# Arizona
final_df2[(final_df2['sale_buy']=='For Sale')&
            (final_df2['sale_type']=='Private Party')&
             (final_df2['Background_Check']=='No')&
         (final_df2['State']=='Arizona')]['ET_Firearm_Type'].value_counts()

Handguns                149732
Rifles                   63605
Assault-style Rifles     34641
Shotguns                 18606
Name: ET_Firearm_Type, dtype: int64

In [204]:
# Handgun
149732/3

49910.666666666664

In [203]:
final_df2[(final_df2['sale_buy']=='For Sale')&
            (final_df2['sale_type']=='Private Party')&
             (final_df2['Background_Check']=='No')&
         (final_df2['State']=='Arizona')]['County'].value_counts()

Maricopa        186691
Pima             36451
Undetermined     14729
Yavapai          11455
Coconino          4299
Yuma              3551
Mohave            2838
Cochise           2284
Gila              1943
Navajo            1167
Pinal              970
Apache              69
Graham              60
Santa Cruz          40
Greenlee            23
La Paz              11
Saint Louis          1
Bell                 1
Guilford             1
Name: County, dtype: int64

## Dashboard 5

In [206]:
# ohio
len(final_df2[(final_df2['sale_buy']=='For Sale')&
            (final_df2['sale_type']=='Private Party')&
             (final_df2['Background_Check']=='No')&
         (final_df2['State']=='Ohio')])

392946